/* ============================================================
   Visual Prompt Atlas — 视觉提示词图库
   app.js · i18n (中/EN) + Prompt Checker + Recipe Card + Library
   Data: window.PROMPT_ATLAS (core-data.js, generated by build.ps1)
   ============================================================ */
(function () {
  'use strict';

  var ATLAS = window.PROMPT_ATLAS;
  var SLOTS = ATLAS.slots.slice().sort(function (a, b) { return a.order - b.order; });
  var ATOMS = ATLAS.atoms;
  var BY_SLOT = ATLAS.bySlot || {};
  var LIB = window.PromptAtlasLib || null;

  /* ---------------- i18n ---------------- */
  var I18N = {
    zh: {
      brand: '视觉提示词图库',
      'tab-checker': '🔍 提示词体检仪',
      'tab-recipe': '🧪 视觉配方卡',
      'tab-library': '📚 词库浏览',
      'checker-title': '提示词体检仪',
      'checker-sub': '贴入你的提示词，10 秒输出「9 槽位缺漏报告」——没写的槽位，是你留给模型的自由发挥空间。',
      'checker-ph': '例如：a girl walking in cyberpunk city, neon lights, close-up, shallow depth of field, slow motion（中英文均可）',
      'checker-run': '开始体检',
      'btn-clear': '清空',
      'checker-ex-good': '填入高分示例',
      'checker-ex-bad': '填入“裸奔”示例',
      'checker-hint': '检测基于词库收录词条（中英文均可识别）；词库之外的描述不影响检测，报告只统计已收录词条。',
      'mode-label': '模式',
      'mode-image': '🖼️ 图片',
      'mode-video': '🎬 视频',
      'report-empty': '等待输入…',
      'report-score': '确定性得分',
      'grade-1': '高确定性 · 指哪打哪',
      'grade-2': '中确定性 · 基本可控',
      'grade-3': '低确定性 · 开始靠运气',
      'grade-4': '危险区 · 大量留白交给模型',
      'grade-short-1': '高确定性',
      'grade-short-2': '中确定性',
      'grade-short-3': '低确定性',
      'grade-short-4': '危险区',
      'cov-label': '槽位覆盖率',
      'missing-label': '未指定',
      'na-tag': '不适用',
      'na-label': '不适用',
      'na-note': '图片模式：运镜不适用，按 {n} 个适用槽位计算',
      'implied-tip': '由原文词条蕴含（如雨夜 ⟹ 夜晚），仅计覆盖、不重复计分',
      'macro-badge': '复合词',
      'est-badge': '估计',
      'bench-badge': '实测',
      'macro-expands': '可拆解为',
      'uncertain-title': '⚠️ 不确定源（低确定性词条）',
      'uncertain-desc': '以下词条在模型里经常「说了白说」，建议替换或补强：',
      'share-btn': '📤 分享体检报告',
      'suggest-maybe': '⚠️ 疑似已描述',
      'suggest-conflict': '冲突',
      'conflict-tip': '该词条与原文描述冲突，已禁用',
      'opt-btn': '🚀 一键生成优化版',
      'opt-title': '优化版提示词（冲突过滤 + 结构化解读）',
      'opt-add': '➕ 新增',
      'opt-skip': '⛔ 跳过（冲突）',
      'opt-maybe-line': '疑似已描述，无需新增',
      'opt-none': '未指定 · 无建议（保留自由发挥）',
      'opt-note': '注：{n} 个槽位疑似已用自由文本描述，实际确定性可能高于得分',
      'opt-note-short': '注：{n} 槽疑似已描述',
      'opt-copy': '📋 复制优化版',
      'opt-covered': '✅ 原文含',
      'opt-zh-title': '中文槽位解读',
      'opt-complete': '✅ 体检结论：提示词已完整，无需修改（优化版 = 原文）',
      'opt-prefix-note': '注：新增词条已置于开头作为全局前缀（长提示词尾部权重低）',
      'copy-ok': '已复制到剪贴板 ✓',
      'copy-fail': '复制失败，请手动复制',
      'input-empty': '请先贴入提示词',
      'recipe-title': '视觉配方卡生成器',
      'recipe-sub': '按 9 槽位选词拼装提示词，实时预览配方卡，一键复制中英文。',
      'f-subject': '主体 Subject',
      'f-subject-ph': 'a young woman / 一位年轻女子',
      'f-action': '动作 Action',
      'f-action-ph': 'walking in the rain / 在雨中行走',
      'f-scene': '场景 Scene',
      'f-scene-ph': 'cyberpunk city street / 赛博朋克城市街头',
      'btn-random': '🎲 随机配方',
      'btn-reset': '重置',
      'out-en': 'English Prompt',
      'out-zh': '中文提示词',
      'out-card': '配方卡文本（可分享）',
      'btn-copy': '复制',
      'card-brand': '视觉配方卡 · Visual Prompt Atlas',
      'card-score': '配方确定性',
      'card-img-note': '示意图占位 · 接入生图 API 后替换为真实画面',
      'card-empty': '从左侧选择词条，实时生成配方卡',
      'card-slots': '槽位覆盖',
      'lib-title': '词库浏览',
      'lib-sub-prefix': '共',
      'lib-sub-mid': '个原子词条 · 9 大槽位 · 确定性分数',
      'lib-legend': '≥80 高 · 60–79 中 · <60 低',
      'lib-search-ph': '搜索词条（中/英文）',
      'lib-all': '全部',
      'lib-no-result': '没有匹配的词条',
      footer: '视觉提示词图库 · Visual Prompt Atlas · 本地原型 · 数据源 core.json（修改后运行 build.ps1 同步）· 图片/视频生成 API 接口已预留'
    },
    en: {
      brand: 'Visual Prompt Atlas',
      'tab-checker': '🔍 Prompt Checker',
      'tab-recipe': '🧪 Recipe Card',
      'tab-library': '📚 Library',
      'checker-title': 'Prompt Checker',
      'checker-sub': 'Paste your prompt and get a 9-slot coverage report in 10 seconds — slots you leave blank are creative freedom you hand to the model.',
      'checker-ph': 'e.g. a girl walking in cyberpunk city, neon lights, close-up, shallow depth of field, slow motion (EN/中文 both work)',
      'checker-run': 'Run Check',
      'btn-clear': 'Clear',
      'checker-ex-good': 'Load a good example',
      'checker-ex-bad': 'Load a "naked" example',
      'checker-hint': 'Detection matches terms registered in the dictionary (Chinese and English). Words outside the dictionary are ignored — the report only counts registered terms.',
      'mode-label': 'Mode',
      'mode-image': '🖼️ Image',
      'mode-video': '🎬 Video',
      'report-empty': 'Waiting for input…',
      'report-score': 'Determinism Score',
      'grade-1': 'High determinism · you get what you asked',
      'grade-2': 'Medium determinism · mostly controllable',
      'grade-3': 'Low determinism · luck is involved',
      'grade-4': 'Danger zone · lots left to the model',
      'grade-short-1': 'High determinism',
      'grade-short-2': 'Medium determinism',
      'grade-short-3': 'Low determinism',
      'grade-short-4': 'Danger zone',
      'cov-label': 'Slot coverage',
      'missing-label': 'Unspecified',
      'na-tag': 'N/A',
      'na-label': 'Not applicable',
      'na-note': 'Image mode: camera movement N/A, scored over {n} applicable slots',
      'implied-tip': 'Implied by another term in the prompt (e.g. rainy night ⟹ night); counts coverage once',
      'macro-badge': 'macro',
      'est-badge': 'estimate',
      'bench-badge': 'benchmarked',
      'macro-expands': 'expands to',
      'uncertain-title': '⚠️ Uncertain sources (low-determinism terms)',
      'uncertain-desc': 'These terms often fail to produce the intended effect. Consider replacing or reinforcing them:',
      'share-btn': '📤 Share report',
      'suggest-maybe': '⚠️ Likely described',
      'suggest-conflict': 'conflict',
      'conflict-tip': 'This term conflicts with your prompt (disabled)',
      'opt-btn': '🚀 Generate optimized version',
      'opt-title': 'Optimized prompt (conflicts filtered, structured breakdown)',
      'opt-add': '➕ Added',
      'opt-skip': '⛔ Skipped (conflict)',
      'opt-maybe-line': 'likely already described — nothing added',
      'opt-none': 'unspecified · no suggestion (freedom preserved)',
      'opt-note': 'Note: {n} slot(s) appear described in free text; real determinism may exceed the score',
      'opt-note-short': 'Note: {n} slot(s) likely described',
      'opt-copy': '📋 Copy optimized version',
      'opt-covered': '✅ in original',
      'opt-zh-title': 'Slot breakdown (中文)',
      'opt-complete': '✅ Verdict: your prompt is complete, no changes needed (optimized = original)',
      'opt-prefix-note': 'Note: additions are placed at the front as global directives (tail weight is low in long prompts)',
      'copy-ok': 'Copied to clipboard ✓',
      'copy-fail': 'Copy failed, please copy manually',
      'input-empty': 'Please paste a prompt first',
      'recipe-title': 'Visual Recipe Card',
      'recipe-sub': 'Assemble a prompt slot by slot, preview the card live, copy in Chinese or English with one click.',
      'f-subject': 'Subject',
      'f-subject-ph': 'a young woman / 一位年轻女子',
      'f-action': 'Action',
      'f-action-ph': 'walking in the rain / 在雨中行走',
      'f-scene': 'Scene',
      'f-scene-ph': 'cyberpunk city street / 赛博朋克城市街头',
      'btn-random': '🎲 Random recipe',
      'btn-reset': 'Reset',
      'out-en': 'English Prompt',
      'out-zh': 'Chinese Prompt',
      'out-card': 'Shareable card text',
      'btn-copy': 'Copy',
      'card-brand': 'VISUAL RECIPE CARD · PROMPT ATLAS',
      'card-score': 'Recipe determinism',
      'card-img-note': 'Placeholder — replaced by a real generated frame once an image API is connected',
      'card-empty': 'Pick atoms on the left to build your card',
      'card-slots': 'Slots covered',
      'lib-title': 'Library',
      'lib-sub-prefix': 'Total:',
      'lib-sub-mid': 'atoms · 9 slots · determinism score',
      'lib-legend': '≥80 high · 60–79 mid · <60 low',
      'lib-search-ph': 'Search terms (EN/中文)',
      'lib-all': 'All',
      'lib-no-result': 'No matching terms',
      footer: 'Visual Prompt Atlas · local prototype · data source core.json (edit then run build.ps1 to sync) · image/video API hooks reserved'
    }
  };

  function detectLang() {
    try {
      var saved = localStorage.getItem('prompt-atlas-lang');
      if (saved === 'zh' || saved === 'en') return saved;
    } catch (e) { /* ignore */ }
    var nav = (navigator.language || 'en').toLowerCase();
    return nav.indexOf('zh') === 0 ? 'zh' : 'en';
  }
  var lang = detectLang();

  function t(key) {
    if (I18N[lang] && I18N[lang][key] !== undefined) return I18N[lang][key];
    if (I18N.zh[key] !== undefined) return I18N.zh[key];
    return key;
  }
  function term(o) { return (o && o[lang]) ? o[lang] : (o && o.zh); }
  function atomName(a) { return term({ zh: a.zh, en: a.en }); }
  function slotName(s) { return term({ zh: s.zh, en: s.en }); }
  function slotDesc(s) { return term({ zh: s.desc, en: s.descEn }); }

  /* ---------------- dom helpers ---------------- */
  function $(id) { return document.getElementById(id); }
  function el(tag, cls, html) {
    var n = document.createElement(tag);
    if (cls) n.className = cls;
    if (html !== undefined) n.innerHTML = html;
    return n;
  }
  function readScore(a) { return (a.score && typeof a.score === 'object') ? a.score.value : a.score; }
  function scoreClass(s) { return s >= 80 ? 'high' : (s >= 60 ? 'mid' : 'low'); }
  function scoreBadgeHtml(x) {
    var s = (typeof x === 'object' && x !== null) ? readScore(x) : x;
    return '<span class="score ' + scoreClass(s) + '">' + s + '</span>';
  }

  var toastTimer = null;
  function toast(msg, isErr) {
    var t = $('toast');
    if (!t) { t = el('div', 'toast'); t.id = 'toast'; document.body.appendChild(t); }
    t.textContent = msg;
    t.className = 'toast show' + (isErr ? ' err' : '');
    clearTimeout(toastTimer);
    toastTimer = setTimeout(function () { t.className = 'toast'; }, 2200);
  }
  function copyText(text) {
    function fallback() {
      try {
        var ta = document.createElement('textarea');
        ta.value = text;
        ta.style.position = 'fixed';
        ta.style.opacity = '0';
        document.body.appendChild(ta);
        ta.select();
        var ok = document.execCommand('copy');
        document.body.removeChild(ta);
        toast(ok ? t('copy-ok') : t('copy-fail'), !ok);
      } catch (e) { toast(t('copy-fail'), true); }
    }
    if (navigator.clipboard && navigator.clipboard.writeText) {
      navigator.clipboard.writeText(text).then(function () { toast(t('copy-ok')); }, fallback);
    } else { fallback(); }
  }

  /* ---------------- static i18n & tabs ---------------- */
  function applyStatic() {
    var nodes = document.querySelectorAll('[data-i18n]');
    for (var i = 0; i < nodes.length; i++) {
      var key = nodes[i].getAttribute('data-i18n');
      var val = t(key);
      if (val) nodes[i].textContent = val;
    }
    var phs = document.querySelectorAll('[data-i18n-ph]');
    for (var j = 0; j < phs.length; j++) {
      phs[j].setAttribute('placeholder', t(phs[j].getAttribute('data-i18n-ph')));
    }
    document.documentElement.lang = lang === 'zh' ? 'zh-CN' : 'en';
    var toggle = $('lang-toggle');
    if (toggle) toggle.textContent = lang === 'zh' ? '🌐 EN' : '🌐 中文';
  }

  function switchTab(name) {
    var buttons = document.querySelectorAll('#tabs button');
    for (var i = 0; i < buttons.length; i++) {
      buttons[i].className = buttons[i].getAttribute('data-tab') === name ? 'active' : '';
    }
    var views = document.querySelectorAll('.view');
    for (var j = 0; j < views.length; j++) {
      views[j].className = views[j].id === 'view-' + name ? 'view active' : 'view';
    }
  }

  /* ================= Prompt Checker / 体检仪 ================= */
  var lastAnalysis = null;
  var checkMode = 'video';
  var EXAMPLES = {
    good: 'a young woman walking in the rain, golden hour, tracking shot, close-up, symmetrical composition, teal and orange, anime style, serene, rainy night, shallow depth of field, slow motion',
    bad: 'a girl in a city, cinematic'
  };


  function shareText(r) {
    var coveredNames = r.covered.map(function (s) { return slotName(s); }).join('、');
    var missingNames = r.missing.map(function (s) { return slotName(s); }).join('、');
    var lines = [];
    lines.push('【' + t('checker-title') + '】' + t('report-score') + ' ' + r.score + '/100（' + t('grade-short-' + r.grade) + '）');
    lines.push('✅ ' + r.covered.length + '/' + r.applicable.length + ' ' + t('cov-label') + '：' + (coveredNames || '—'));
    if (r.missing.length) lines.push('◻️ ' + t('missing-label') + '：' + missingNames);
    if (r.notApplicable.length) lines.push('➖ ' + t('na-label') + '：' + r.notApplicable.map(function (s) { return slotName(s); }).join('、'));
    if (r.uncertain.length) {
      var unc = r.uncertain.map(function (a) { return atomName(a); }).join('、');
      lines.push('⚠️ ' + t('uncertain-title') + '：' + unc);
    }
    lines.push('—— ' + t('brand') + ' Visual Prompt Atlas');
    return lines.join('\n');
  }

  function renderReport(r) {
    var box = $('checker-report');
    var pct = Math.round(r.coverage * 100);
    var html = '';
    html += '<div class="rep-head">';
    html += '<div class="rep-score" style="--p:' + pct + '"><span class="score-num">' + r.score + '</span><span class="score-max">/100</span></div>';
    html += '<div class="rep-meta">';
    html += '<div class="rep-grade grade-' + r.grade + '">' + t('grade-' + r.grade) + '</div>';
    html += '<div class="rep-cov"><span>' + t('cov-label') + '</span><div class="bar"><div class="bar-fill" style="width:' + pct + '%"></div></div><b>' + r.covered.length + '/' + r.applicable.length + '</b></div>';
    if (r.maybeCount > 0) {
      html += '<div class="rep-maybe-note">' + t('opt-note-short').replace('{n}', r.maybeCount) + '</div>';
    }
    if (r.notApplicable.length > 0) {
      html += '<div class="rep-na-note">' + t('na-note').replace('{n}', r.applicable.length) + '</div>';
    }
    html += '</div></div>';
    html += '<div class="rep-slots">';
    SLOTS.forEach(function (s) {
      var atoms = r.perSlot[s.id];
      var isNA = false;
      for (var na = 0; na < r.notApplicable.length; na++) {
        if (r.notApplicable[na].id === s.id) { isNA = true; break; }
      }
      if (atoms.length) {
        html += '<div class="rep-slot ok"><div class="rep-slot-name">' + slotName(s) + '</div><div class="rep-slot-body">';
        atoms.forEach(function (a) {
          html += '<span class="chip found"><b>' + atomName(a) + '</b><span class="chip-en">' + a.en + '</span>' + scoreBadgeHtml(a) + '</span>';
        });
        var implied = r.impliedBySlot[s.id] || [];
        implied.forEach(function (a) {
          html += '<span class="chip implied" title="' + t('implied-tip') + '">⇐ ' + atomName(a) + ' <span class="chip-en">' + a.en + '</span></span>';
        });
        html += '</div></div>';
      } else if (isNA) {
        html += '<div class="rep-slot na"><div class="rep-slot-name">' + slotName(s) + '</div><div class="rep-slot-body">';
        html += '<span class="na-tag">' + t('na-tag') + '</span>';
        html += '</div></div>';
      } else {
        var detail = null;
        for (var k = 0; k < r.missingDetail.length; k++) {
          if (r.missingDetail[k].slot.id === s.id) { detail = r.missingDetail[k]; break; }
        }
        var isMaybe = detail && detail.maybe;
        html += '<div class="rep-slot ' + (isMaybe ? 'maybe' : 'miss') + '"><div class="rep-slot-name">' + slotName(s) + '</div><div class="rep-slot-body">';
        html += '<span class="miss-tag">' + (isMaybe ? t('suggest-maybe') : t('missing-label')) + '</span>';
        if (detail) {
          detail.suggs.forEach(function (x) {
            var a = x.atom;
            if (x.conflict) {
              html += '<span class="chip conflict-chip" title="' + t('conflict-tip') + '">' + atomName(a) + ' <span class="chip-en">' + a.en + '</span>' + scoreBadgeHtml(a.score) + '<span class="conflict-badge">' + t('suggest-conflict') + '</span></span>';
            } else {
              html += '<span class="chip sugg" data-add="' + a.en.replace(/"/g, '&quot;') + '">+ ' + atomName(a) + ' <span class="chip-en">' + a.en + '</span></span>';
            }
          });
        }
        html += '</div></div>';
      }
    });
    html += '</div>';
    if (r.uncertain.length) {
      html += '<div class="rep-uncertain"><div class="rep-unc-title">' + t('uncertain-title') + '</div><div class="rep-unc-desc">' + t('uncertain-desc') + '</div>';
      r.uncertain.forEach(function (a) {
        html += '<span class="chip low-chip">' + atomName(a) + ' <span class="chip-en">' + a.en + '</span>' + scoreBadgeHtml(a.score) + '</span>';
      });
      html += '</div>';
    }
    html += '<div class="btn-row"><button id="share-report" class="btn primary">' + t('share-btn') + '</button><button id="opt-report" class="btn">' + t('opt-btn') + '</button></div>';
    box.innerHTML = html;

    var suggs = box.querySelectorAll('.chip.sugg');
    for (var i = 0; i < suggs.length; i++) {
      suggs[i].addEventListener('click', function () {
        var add = this.getAttribute('data-add');
        var ta = $('checker-input');
        ta.value = (ta.value.trim() ? ta.value.replace(/\s*$/, '') + ', ' : '') + add;
        runCheck();
      });
    }
    $('share-report').addEventListener('click', function () { copyText(shareText(r)); });
    $('opt-report').addEventListener('click', function () {
      var existing = box.querySelector('.opt-block');
      if (existing) { existing.parentNode.removeChild(existing); return; }
      var opt = buildOptimized(r);
      var div = el('div', 'opt-block');
      div.innerHTML = renderOptimizedHtml(opt, r);
      var btnRow = box.querySelector('.btn-row');
      btnRow.parentNode.insertBefore(div, btnRow);
      if (div.scrollIntoView) div.scrollIntoView({ behavior: 'smooth', block: 'center' });
      var copyBtn = div.querySelector('[data-optcopy]');
      if (copyBtn) copyBtn.addEventListener('click', function () { copyText(optCopyText(opt, r)); });
    });
  }

  function buildOptimized(r) {
    return LIB.buildOptimized(ATLAS, r);
  }

  function slotById(id) {
    for (var i = 0; i < SLOTS.length; i++) if (SLOTS[i].id === id) return SLOTS[i];
    return { id: id, zh: id, en: id, desc: '', descEn: '' };
  }

  function renderOptimizedHtml(opt, r) {
    var html = '';
    html += '<div class="opt-title">' + t('opt-title') + '</div>';
    if (opt.added.length === 0 && opt.skipped.length === 0) {
      html += '<div class="opt-complete">' + t('opt-complete') + '</div>';
    }
    html += '<div class="opt-en">' + opt.en + '</div>';
    var zhLines = [];
    r.covered.forEach(function (s) {
      var names = r.perSlot[s.id].map(atomName).join('、');
      zhLines.push(slotName(s) + '：' + t('opt-covered') + ' ' + names);
    });
    opt.maybeSlots.forEach(function (id) { zhLines.push(slotName(slotById(id)) + '：' + t('opt-maybe-line')); });
    opt.added.forEach(function (a) { zhLines.push(slotName(slotById(a.slot)) + '：' + t('opt-add') + ' ' + atomName(a) + '（' + a.en + '）'); });
    opt.noSuggestion.forEach(function (id) { zhLines.push(slotName(slotById(id)) + '：' + t('opt-none')); });
    html += '<div class="opt-zh">' + zhLines.join('<br>') + '</div>';
    if (opt.maybeCount) html += '<div class="opt-note">' + t('opt-note').replace('{n}', opt.maybeCount) + '</div>';
    html += '<div class="opt-stats">' + t('opt-add') + '：' + opt.added.length + ' · ' + t('opt-skip') + '：' + opt.skipped.length + '</div>';
    if (opt.longPrefix) html += '<div class="opt-note">' + t('opt-prefix-note') + '</div>';
    html += '<button class="btn primary" data-optcopy="1">' + t('opt-copy') + '</button>';
    return html;
  }

  function optCopyText(opt, r) {
    var lines = [];
    lines.push('🎬 ' + t('opt-title'));
    lines.push('EN: ' + opt.en);
    lines.push(t('opt-zh-title') + '：');
    r.covered.forEach(function (s) {
      lines.push('  ' + slotName(s) + '：' + t('opt-covered') + ' ' + r.perSlot[s.id].map(atomName).join('、'));
    });
    opt.maybeSlots.forEach(function (id) { lines.push('  ' + slotName(slotById(id)) + '：' + t('opt-maybe-line')); });
    opt.added.forEach(function (a) { lines.push('  ' + slotName(slotById(a.slot)) + '：' + t('opt-add') + ' ' + atomName(a) + '（' + a.en + '）'); });
    opt.noSuggestion.forEach(function (id) { lines.push('  ' + slotName(slotById(id)) + '：' + t('opt-none')); });
    if (opt.maybeCount) lines.push(t('opt-note').replace('{n}', opt.maybeCount));
    if (opt.longPrefix) lines.push(t('opt-prefix-note'));
    lines.push('—— ' + t('brand') + ' Visual Prompt Atlas');
    return lines.join('\n');
  }

  function runCheck() {
    var text = $('checker-input').value.trim();
    if (!text) { toast(t('input-empty'), true); return; }
    lastAnalysis = LIB.analyze(ATLAS, text, checkMode);
    renderReport(lastAnalysis);
  }

  /* ================= Recipe Card / 配方卡 ================= */
  var recipe = { subject: '', action: '', scene: '', picks: {} };
  var SAMPLES = {
    zh: {
      subjects: ['一位年轻女子', '一只白猫', '一位老者', '一名宇航员', '一个旧机器人'],
      actions: ['在雨中行走', '静静站立', '缓缓转身', '奔跑追逐', '抬头仰望'],
      scenes: ['赛博朋克城市街头', '雪山之巅', '老上海弄堂', '废弃的火车站', '海边灯塔']
    },
    en: {
      subjects: ['a young woman', 'a white cat', 'an old man', 'an astronaut', 'a rusty robot'],
      actions: ['walking in the rain', 'standing still', 'turning around slowly', 'running and chasing', 'looking up at the sky'],
      scenes: ['a cyberpunk city street', 'a snowy mountain peak', 'an old Shanghai alley', 'an abandoned train station', 'a lighthouse by the sea']
    }
  };

  function renderPickers() {
    var box = $('slot-pickers');
    box.innerHTML = '';
    SLOTS.forEach(function (s) {
      var wrap = el('div', 'picker');
      var head = el('div', 'picker-head');
      head.innerHTML = '<span class="picker-name">' + slotName(s) + '</span><span class="picker-desc">' + slotDesc(s) + '</span>';
      var chips = el('div', 'picker-chips');
      (BY_SLOT[s.id] || []).forEach(function (a) {
        var c = el('button', 'chip' + (recipe.picks[s.id] === a.id ? ' sel' : ''));
        c.setAttribute('data-atom', a.id);
        c.innerHTML = atomName(a) + ' <span class="chip-en">' + a.en + '</span>' + scoreBadgeHtml(a.score);
        c.addEventListener('click', function () {
          recipe.picks[s.id] = (recipe.picks[s.id] === a.id) ? null : a.id;
          renderPickers();
          renderPreview();
        });
        chips.appendChild(c);
      });
      wrap.appendChild(head);
      wrap.appendChild(chips);
      box.appendChild(wrap);
    });
  }

  function atomById(id) {
    for (var i = 0; i < ATOMS.length; i++) if (ATOMS[i].id === id) return ATOMS[i];
    return null;
  }

  function pickedAtoms() {
    var out = [];
    SLOTS.forEach(function (s) {
      var a = recipe.picks[s.id] ? atomById(recipe.picks[s.id]) : null;
      if (a) out.push(a);
    });
    return out;
  }

  function assemble() {
    var baseEn = [recipe.subject, recipe.action, recipe.scene].filter(Boolean).join(' ');
    var partsEn = pickedAtoms().map(function (a) { return a.en; });
    var en = (baseEn ? baseEn + ', ' : '') + partsEn.join(', ');
    var baseZh = recipe.subject + (recipe.action || '') + (recipe.scene ? '，' + recipe.scene : '');
    var partsZh = pickedAtoms().map(function (a) { return slotName(slotOf(a)) + '：' + a.zh; });
    var zh = (baseZh ? baseZh + '。' : '') + partsZh.join('，') + (partsZh.length ? '。' : '');
    var atoms = pickedAtoms();
    var score = atoms.length ? Math.round(atoms.reduce(function (s, a) { return s + readScore(a); }, 0) / atoms.length) : 0;
    return { en: en || '—', zh: zh || '—', score: score, atoms: atoms };
  }
  function slotOf(a) {
    for (var i = 0; i < SLOTS.length; i++) if (SLOTS[i].id === a.slot) return SLOTS[i];
    return { zh: a.slot, en: a.slot, desc: '', descEn: '' };
  }

  function cardText(a) {
    var lines = [];
    lines.push('🎬 ' + t('card-brand'));
    if (recipe.subject) lines.push(t('f-subject') + '：' + recipe.subject);
    if (recipe.action) lines.push(t('f-action') + '：' + recipe.action);
    if (recipe.scene) lines.push(t('f-scene') + '：' + recipe.scene);
    a.atoms.forEach(function (x) { lines.push(slotName(slotOf(x)) + '：' + atomName(x) + '（' + x.en + '）'); });
    lines.push(t('card-score') + '：' + a.score + '/100 · ' + t('card-slots') + '：' + a.atoms.length + '/' + SLOTS.length);
    lines.push('—— ' + t('brand') + ' Visual Prompt Atlas');
    return lines.join('\n');
  }

  function gradClass() {
    var color = recipe.picks.color ? atomById(recipe.picks.color) : null;
    if (color) {
      var map = {
        'cyberpunk-palette': 'grad-cyberpunk', monochrome: 'grad-mono', pastel: 'grad-pastel',
        'high-sat': 'grad-vivid', desaturated: 'grad-desat', 'teal-orange': 'grad-teal'
      };
      if (map[color.id]) return map[color.id];
    }
    var time = recipe.picks.time ? atomById(recipe.picks.time) : null;
    if (time) {
      var tmap = { dawn: 'grad-dawn', dusk: 'grad-dusk', 'blue-hour': 'grad-blue-hour', night: 'grad-night', 'rainy-night': 'grad-rainy-night' };
      if (tmap[time.id]) return tmap[time.id];
    }
    return 'grad-default';
  }

  function renderPreview() {
    var box = $('card-preview');
    var a = assemble();
    var hasAny = recipe.subject || recipe.action || recipe.scene || a.atoms.length > 0;
    if (!hasAny) {
      box.innerHTML = '<div class="card-empty">' + t('card-empty') + '</div>';
    } else {
      var midMain = (recipe.subject ? recipe.subject + ' ' : '') + (recipe.action ? recipe.action : '') + (recipe.scene ? ' @ ' + recipe.scene : '');
      var chipsHtml = a.atoms.map(function (x) { return '<span class="cc">' + atomName(x) + '</span>'; }).join('');
      box.innerHTML =
        '<div class="card-stage ' + gradClass() + '">' +
        '<div class="card-top"><span class="card-brand">' + t('card-brand') + '</span>' +
        '<span class="card-scorepill">' + a.score + '/100</span></div>' +
        '<div class="card-mid"><div class="card-main">' + midMain +
        '<small>' + t('card-score') + ': ' + a.score + '/100 · ' + t('card-slots') + ': ' + a.atoms.length + '/' + SLOTS.length + '</small></div>' +
        '<span class="card-img-note">' + t('card-img-note') + '</span></div>' +
        '<div class="card-chips">' + chipsHtml + '</div>' +
        '</div>' +
        '<div class="card-foot"><span>' + t('card-score') + '</span><b>' + a.score + '/100</b></div>';
    }
    $('prompt-en').textContent = a.en;
    $('prompt-zh').textContent = a.zh;
    $('prompt-card').textContent = cardText(a);
  }

  function randomRecipe() {
    var s = SAMPLES[lang] || SAMPLES.zh;
    function pick(arr) { return arr[Math.floor(Math.random() * arr.length)]; }
    recipe.subject = pick(s.subjects);
    recipe.action = pick(s.actions);
    recipe.scene = pick(s.scenes);
    recipe.picks = {};
    SLOTS.forEach(function (slot) {
      var list = BY_SLOT[slot.id] || [];
      if (list.length) recipe.picks[slot.id] = list[Math.floor(Math.random() * list.length)].id;
    });
    $('recipe-subject').value = recipe.subject;
    $('recipe-action').value = recipe.action;
    $('recipe-scene').value = recipe.scene;
    renderPickers();
    renderPreview();
  }
  function resetRecipe() {
    recipe = { subject: '', action: '', scene: '', picks: {} };
    $('recipe-subject').value = '';
    $('recipe-action').value = '';
    $('recipe-scene').value = '';
    renderPickers();
    renderPreview();
  }

  /* ================= Library / 词库 ================= */
  var libState = { slot: 'all', q: '' };

  function renderLibrary() {
    $('lib-count').textContent = String(ATOMS.length);
    var bar = $('lib-slots');
    bar.innerHTML = '';
    var allBtn = el('button', libState.slot === 'all' ? 'active' : '', t('lib-all'));
    allBtn.addEventListener('click', function () { libState.slot = 'all'; renderLibrary(); });
    bar.appendChild(allBtn);
    SLOTS.forEach(function (s) {
      var b = el('button', libState.slot === s.id ? 'active' : '', slotName(s));
      b.addEventListener('click', function () { libState.slot = s.id; renderLibrary(); });
      bar.appendChild(b);
    });

    var grid = $('lib-grid');
    grid.innerHTML = '';
    var q = libState.q.trim().toLowerCase();
    var list = ATOMS.filter(function (a) {
      if (libState.slot !== 'all' && a.slot !== libState.slot) return false;
      if (!q) return true;
      return a.zh.toLowerCase().indexOf(q) !== -1 || a.en.toLowerCase().indexOf(q) !== -1 || a.desc.indexOf(q) !== -1 || (a.descEn && a.descEn.toLowerCase().indexOf(q) !== -1);
    });
    if (!list.length) {
      grid.appendChild(el('div', 'lib-empty', t('lib-no-result')));
      return;
    }
    list.forEach(function (a) {
      var card = el('div', 'atom-card');
      var meta = '';
      if (a.type === 'macro') meta += '<span class="macro-badge">' + t('macro-badge') + '</span>';
      if (a.score && a.score.status === 'benchmarked') meta += '<span class="status-badge bench">' + t('bench-badge') + '</span>';
      else meta += '<span class="status-badge est">' + t('est-badge') + '</span>';
      var expandHtml = '';
      if (a.relations && a.relations.expandsTo && a.relations.expandsTo.length) {
        var names = a.relations.expandsTo.map(function (id) {
          var t = LIB ? LIB.atomById(ATLAS, id) : null;
          return t ? term({ zh: t.zh, en: t.en }) : id;
        }).join('、');
        expandHtml = '<div class="atom-meta">' + t('macro-expands') + '：' + names + '</div>';
      }
      card.innerHTML =
        '<div class="atom-head"><span class="atom-zh">' + a.zh + meta + '</span>' + scoreBadgeHtml(a) + '</div>' +
        '<div class="atom-en">' + a.en + '</div>' +
        '<div class="atom-desc">' + term({ zh: a.desc, en: a.descEn }) + '</div>' +
        expandHtml +
        '<div class="atom-example">' + a.example + '</div>';
      grid.appendChild(card);
    });
  }

  /* ================= global render & events ================= */
  function renderAll() {
    applyStatic();
    if (lastAnalysis) renderReport(lastAnalysis);
    renderPickers();
    renderPreview();
    renderLibrary();
  }

  function wire() {
    $('lang-toggle').addEventListener('click', function () {
      lang = lang === 'zh' ? 'en' : 'zh';
      try { localStorage.setItem('prompt-atlas-lang', lang); } catch (e) { /* ignore */ }
      renderAll();
    });
    var tabs = document.querySelectorAll('#tabs button');
    for (var i = 0; i < tabs.length; i++) {
      tabs[i].addEventListener('click', function () { switchTab(this.getAttribute('data-tab')); });
    }
    $('checker-run').addEventListener('click', runCheck);
    var modeImage = $('mode-image');
    var modeVideo = $('mode-video');
    function setMode(mode) {
      checkMode = mode;
      if (modeImage) modeImage.className = 'mode-btn' + (mode === 'image' ? ' active' : '');
      if (modeVideo) modeVideo.className = 'mode-btn' + (mode === 'video' ? ' active' : '');
      if (lastAnalysis) runCheck();
    }
    if (modeImage) modeImage.addEventListener('click', function () { setMode('image'); });
    if (modeVideo) modeVideo.addEventListener('click', function () { setMode('video'); });
    $('checker-clear').addEventListener('click', function () {
      $('checker-input').value = '';
      lastAnalysis = null;
      $('checker-report').innerHTML = '<div class="report-empty" data-i18n="report-empty">' + t('report-empty') + '</div>';
    });
    $('checker-example').addEventListener('click', function () { $('checker-input').value = EXAMPLES.good; runCheck(); });
    $('checker-example-bad').addEventListener('click', function () { $('checker-input').value = EXAMPLES.bad; runCheck(); });
    $('recipe-random').addEventListener('click', randomRecipe);
    $('recipe-reset').addEventListener('click', resetRecipe);
    ['recipe-subject', 'recipe-action', 'recipe-scene'].forEach(function (id) {
      $(id).addEventListener('input', function () {
        recipe[id.replace('recipe-', '')] = this.value;
        renderPreview();
      });
    });
    var copyBtns = document.querySelectorAll('[data-copy]');
    for (var j = 0; j < copyBtns.length; j++) {
      copyBtns[j].addEventListener('click', function () {
        copyText($(this.getAttribute('data-copy')).textContent);
      });
    }
    $('lib-search').addEventListener('input', function () { libState.q = this.value; renderLibrary(); });
  }

  renderAll();
  wire();
})();
