/* ============================================================
   Visual Prompt Atlas — 视觉提示词图库
   app.js · i18n (中/EN) + Prompt Checker + Recipe Card + Library
   Data: window.PROMPT_ATLAS (core-data.js, generated by build.ps1)
   ============================================================ */
(function () {
  'use strict';

  var ATLAS = window.PROMPT_ATLAS;
  var SLOTS = ATLAS.slots.slice().sort(function (a, b) { return a.order - b.order; });
  var ATOMS = ATLAS.atoms;
  var BY_SLOT = ATLAS.bySlot || {};
  var LIB = window.PromptAtlasLib || null;
  var REC = window.PROMPT_ATLAS_REC || null;
  var AN = window.AtlasAnalytics || null;

  /* consent-gated analytics wrapper: never throws, never sends before opt-in */
  function trk(name, payload) {
    if (AN && AN.enabled()) { try { AN.track(name, payload); } catch (e) { /* ignore */ } }
  }

  /* ---------------- i18n ---------------- */
  var I18N = {
    zh: {
      brand: '视觉提示词图库',
      'tab-checker': '🔍 提示词体检仪',
      'tab-recipe': '🧪 视觉配方卡',
      'tab-library': '📚 词库浏览',
      'tab-storyboard': '🎞️ 剧本→分镜',
      'checker-title': '提示词体检仪',
      'checker-sub': '贴入你的提示词，10 秒输出「9 槽位缺漏报告」——没写的槽位，是你留给模型的自由发挥空间。',
      'checker-ph': '例如：a girl walking in cyberpunk city, neon lights, close-up, shallow depth of field, slow motion（中英文均可）',
      'checker-run': '开始体检',
      'btn-clear': '清空',
      'checker-ex-good': '填入高分示例',
      'checker-ex-bad': '填入“裸奔”示例',
      'checker-hint': '检测基于词库收录词条（中英文均可识别）；词库之外的描述不影响检测，报告只统计已收录词条。',
      'mode-label': '模式',
      'mode-image': '🖼️ 图片',
      'mode-video': '🎬 视频',
      'report-empty': '等待输入…',
      'profile-title': '提示词控制画像',
      'dim-reliability': '可靠性',
      'dim-coverage': '覆盖率',
      'dim-consistency': '一致性',
      'dim-freedom': '留白',
      'level-label': '控制等级',
      'level-high': '🟢 高控制 · 指哪打哪',
      'level-medium': '🟡 中控制 · 基本可控',
      'level-low': '🔵 低控制 · 大量留白',
      'level-conflict': '🔴 存在冲突 · 先解决矛盾',
      'count-macro': '复合词',
      'sec-conflict': '硬冲突',
      'sec-tension': '软张力',
      'sec-redundant': '冗余',
      'sec-tension-desc': '可以共存，但容易互相削弱，建议明确主次：',
      'sec-redundant-desc': '后一个词已被前一个词蕴含，重复指定不增加控制量：',
      'sec-mismatch-title': '⚠️ 模态不符（视频专属词出现在图片提示词中）',
      'sec-mismatch-desc': '以下词条只适用于视频，不计入覆盖与得分：',
      'time-irrelevant-note': '抽象空间语境 · 时间维度不适用',
      'opt-expand-label': '{macro} 可拆解为',
      'grade-1': '高确定性 · 指哪打哪',
      'grade-2': '中确定性 · 基本可控',
      'grade-3': '低确定性 · 开始靠运气',
      'grade-4': '危险区 · 大量留白交给模型',
      'grade-short-1': '高确定性',
      'grade-short-2': '中确定性',
      'grade-short-3': '低确定性',
      'grade-short-4': '危险区',
      'cov-label': '槽位覆盖率',
      'missing-label': '未指定',
      'na-tag': '不适用',
      'na-label': '不适用',
      'na-note': '图片模式：运镜不适用，按 {n} 个适用槽位计算',
      'implied-tip': '由原文词条蕴含（如雨夜 ⟹ 夜晚），仅计覆盖、不重复计分',
      'macro-badge': '复合词',
      'est-badge': '估计',
      'bench-badge': '实测',
      'macro-expands': '可拆解为',
      'uncertain-title': '⚠️ 不确定源（低确定性词条）',
      'uncertain-desc': '以下词条在模型里经常「说了白说」，建议替换或补强：',
      'share-btn': '📤 分享体检报告',
      'suggest-maybe': '⚠️ 疑似已描述',
      'suggest-conflict': '冲突',
      'conflict-tip': '该词条与原文描述冲突，已禁用',
      'opt-btn': '🚀 一键生成优化版',
      'opt-title': '优化版提示词（冲突过滤 + 结构化解读）',
      'opt-add': '➕ 新增',
      'opt-skip': '⛔ 跳过（冲突）',
      'opt-maybe-line': '疑似已描述，无需新增',
      'opt-none': '未指定 · 无建议（保留自由发挥）',
      'opt-note': '注：{n} 个槽位疑似已用自由文本描述，实际确定性可能高于得分',
      'opt-note-short': '注：{n} 槽疑似已描述',
      'opt-copy': '📋 复制优化版',
      'opt-covered': '✅ 原文含',
      'opt-zh-title': '中文槽位解读',
      'opt-complete': '✅ 体检结论：提示词已完整，无需修改（优化版 = 原文）',
      'opt-prefix-note': '注：新增词条已置于开头作为全局前缀（长提示词尾部权重低）',
      'copy-ok': '已复制到剪贴板 ✓',
      'copy-fail': '复制失败，请手动复制',
      'input-empty': '请先贴入提示词',
      'recipe-title': '视觉配方卡生成器',
      'recipe-sub': '按 9 槽位选词拼装提示词，实时预览配方卡，一键复制中英文。',
      'f-subject': '主体 Subject',
      'f-subject-ph': 'a young woman / 一位年轻女子',
      'f-action': '动作 Action',
      'f-action-ph': 'walking in the rain / 在雨中行走',
      'f-scene': '场景 Scene',
      'f-scene-ph': 'cyberpunk city street / 赛博朋克城市街头',
      'btn-random': '🎲 随机配方',
      'btn-reset': '重置',
      'btn-share-card': '📤 分享配方',
      'share-card-copied': '分享链接已复制 ✓',
      'share-card-loaded': '已载入分享的配方 ✓',
      'share-card-bad': '分享链接无效',
      'evidence-without': '无词对照',
      'evidence-with': '加词效果',
      'evidence-note': '实测证据对 · {model} · {scene} 场景 · 判定 {c}→{t}',
      'out-en': 'English Prompt',
      'out-zh': '中文提示词',
      'out-card': '配方卡文本（可分享）',
      'btn-copy': '复制',
      'card-brand': '视觉配方卡 · Visual Prompt Atlas',
      'card-score': '配方卡 · Control Profile',
      'cp-r': '可靠性',
      'cp-c': '覆盖',
      'cp-s': '一致性',
      'cp-f': '留白',
      'ev-note': '实测 {b}/{t} · 最低证据 {f}',
      'card-img-note': '示意图占位 · 接入生图 API 后替换为真实画面',
      'card-empty': '从左侧选择词条，实时生成配方卡',
      'card-slots': '槽位覆盖',
      'lib-title': '词库浏览',
      'lib-sub-prefix': '共',
      'lib-sub-mid': '个原子词条 · 9 大槽位 · 确定性分数',
      'lib-legend': '≥80 高 · 60–79 中 · <60 低',
      'atom-measured': '依从 {a}% · 基线 {b}% · 增益 +{l}pp',
      'lib-search-ph': '搜索词条（中/英文）',
      'lib-all': '全部',
      'lib-no-result': '没有匹配的词条',
      'ctx-model': '目标模型',
      'ctx-model-any': '不指定（通用）',
      'ctx-scene': '画面类型',
      'ctx-scene-any': '不指定',
      'ctx-note': '建议与词片已按实测数据排序（20 词 · 3 模型 · 6 类画面，未实测词标注「无实测」）',
      'btn-evidence': '🎯 实测推荐',
      'rec-toast': '已按实测填充 {n} 个空槽 ✓',
      'rec-none': '没有可推荐的空槽（槽位已满或候选全冲突）',
      'rec-whiteout': '实测白写',
      'rec-scene-dead': '此画面无效',
      'rec-scene-fit': '+{l}',
      'rec-strong': '强开关',
      'rec-split': '分差 {d}',
      'rec-heuristic': '无实测',
      'rec-conflict': '冲突',
      'consent-title': 'Atlas 会收集匿名化程度有限的产品使用统计，帮助我们改进体检，不包含你的提示词内容。',
      'consent-allow': '允许匿名使用统计',
      'consent-local': '仅本地使用',
      'consent-note': '随时可在页脚或隐私说明中更改',
      'footer-stats': '📊 使用统计',
      'footer-privacy': '🔒 隐私说明',
      'invalid-title': '⚠ 实测无效词',
      'invalid-why-model': '该模型实测低分',
      'invalid-why-scene': '此画面类型实测无效果',
      'invalid-why-whiteout': '实测白写',
      'invalid-why-low': '实测低分',
      'btn-share-card': '🖼️ 生成分享卡',
      'btn-share-card-img': '🖼️ 生成分享卡',
      footer: '视觉提示词图库 · Visual Prompt Atlas · 本地原型 · 数据源 core.json（修改后运行 build.ps1 同步）· 图片/视频生成 API 接口已预留'
    },
    en: {
      brand: 'Visual Prompt Atlas',
      'tab-checker': '🔍 Prompt Checker',
      'tab-recipe': '🧪 Recipe Card',
      'tab-library': '📚 Library',
      'tab-storyboard': '🎞️ Storyboard',
      'checker-title': 'Prompt Checker',
      'checker-sub': 'Paste your prompt and get a 9-slot coverage report in 10 seconds — slots you leave blank are creative freedom you hand to the model.',
      'checker-ph': 'e.g. a girl walking in cyberpunk city, neon lights, close-up, shallow depth of field, slow motion (EN/中文 both work)',
      'checker-run': 'Run Check',
      'btn-clear': 'Clear',
      'checker-ex-good': 'Load a good example',
      'checker-ex-bad': 'Load a "naked" example',
      'checker-hint': 'Detection matches terms registered in the dictionary (Chinese and English). Words outside the dictionary are ignored — the report only counts registered terms.',
      'mode-label': 'Mode',
      'mode-image': '🖼️ Image',
      'mode-video': '🎬 Video',
      'report-empty': 'Waiting for input…',
      'profile-title': 'Prompt Control Profile',
      'dim-reliability': 'Reliability',
      'dim-coverage': 'Coverage',
      'dim-consistency': 'Consistency',
      'dim-freedom': 'Freedom',
      'level-label': 'Control Level',
      'level-high': '🟢 High control',
      'level-medium': '🟡 Medium control',
      'level-low': '🔵 Low control · mostly freedom',
      'level-conflict': '🔴 Conflicts present',
      'count-macro': 'macros',
      'sec-conflict': 'hard conflicts',
      'sec-tension': 'soft tensions',
      'sec-redundant': 'redundant',
      'sec-tension-desc': 'Can coexist but weaken each other; consider clarifying priority:',
      'sec-redundant-desc': 'The second term is implied by the first; repeating adds no control:',
      'sec-mismatch-title': '⚠️ Modality mismatch (video-only terms in an image prompt)',
      'sec-mismatch-desc': 'These terms apply to video only; excluded from coverage and score:',
      'time-irrelevant-note': 'abstract-space context · time N/A',
      'opt-expand-label': '{macro} can be expanded to',
      'grade-1': 'High determinism · you get what you asked',
      'grade-2': 'Medium determinism · mostly controllable',
      'grade-3': 'Low determinism · luck is involved',
      'grade-4': 'Danger zone · lots left to the model',
      'grade-short-1': 'High determinism',
      'grade-short-2': 'Medium determinism',
      'grade-short-3': 'Low determinism',
      'grade-short-4': 'Danger zone',
      'cov-label': 'Slot coverage',
      'missing-label': 'Unspecified',
      'na-tag': 'N/A',
      'na-label': 'Not applicable',
      'na-note': 'Image mode: camera movement N/A, scored over {n} applicable slots',
      'implied-tip': 'Implied by another term in the prompt (e.g. rainy night ⟹ night); counts coverage once',
      'macro-badge': 'macro',
      'est-badge': 'estimate',
      'bench-badge': 'benchmarked',
      'macro-expands': 'expands to',
      'uncertain-title': '⚠️ Uncertain sources (low-determinism terms)',
      'uncertain-desc': 'These terms often fail to produce the intended effect. Consider replacing or reinforcing them:',
      'share-btn': '📤 Share report',
      'suggest-maybe': '⚠️ Likely described',
      'suggest-conflict': 'conflict',
      'conflict-tip': 'This term conflicts with your prompt (disabled)',
      'opt-btn': '🚀 Generate optimized version',
      'opt-title': 'Optimized prompt (conflicts filtered, structured breakdown)',
      'opt-add': '➕ Added',
      'opt-skip': '⛔ Skipped (conflict)',
      'opt-maybe-line': 'likely already described — nothing added',
      'opt-none': 'unspecified · no suggestion (freedom preserved)',
      'opt-note': 'Note: {n} slot(s) appear described in free text; real determinism may exceed the score',
      'opt-note-short': 'Note: {n} slot(s) likely described',
      'opt-copy': '📋 Copy optimized version',
      'opt-covered': '✅ in original',
      'opt-zh-title': 'Slot breakdown (中文)',
      'opt-complete': '✅ Verdict: your prompt is complete, no changes needed (optimized = original)',
      'opt-prefix-note': 'Note: additions are placed at the front as global directives (tail weight is low in long prompts)',
      'copy-ok': 'Copied to clipboard ✓',
      'copy-fail': 'Copy failed, please copy manually',
      'input-empty': 'Please paste a prompt first',
      'recipe-title': 'Visual Recipe Card',
      'recipe-sub': 'Assemble a prompt slot by slot, preview the card live, copy in Chinese or English with one click.',
      'f-subject': 'Subject',
      'f-subject-ph': 'a young woman / 一位年轻女子',
      'f-action': 'Action',
      'f-action-ph': 'walking in the rain / 在雨中行走',
      'f-scene': 'Scene',
      'f-scene-ph': 'cyberpunk city street / 赛博朋克城市街头',
      'btn-random': '🎲 Random recipe',
      'btn-reset': 'Reset',
      'btn-share-card': '📤 Share recipe',
      'share-card-copied': 'Share link copied ✓',
      'share-card-loaded': 'Shared recipe loaded ✓',
      'share-card-bad': 'Invalid share link',
      'evidence-without': 'Without term',
      'evidence-with': 'With term',
      'evidence-note': 'Measured pair · {model} · scene {scene} · judged {c}→{t}',
      'out-en': 'English Prompt',
      'out-zh': 'Chinese Prompt',
      'out-card': 'Shareable card text',
      'btn-copy': 'Copy',
      'card-brand': 'VISUAL RECIPE CARD · PROMPT ATLAS',
      'card-score': 'Recipe Card · Control Profile',
      'cp-r': 'Reliability',
      'cp-c': 'Coverage',
      'cp-s': 'Consistency',
      'cp-f': 'Freedom',
      'ev-note': 'Evidence {b}/{t} benchmarked · floor {f}',
      'card-img-note': 'Placeholder — replaced by a real generated frame once an image API is connected',
      'card-empty': 'Pick atoms on the left to build your card',
      'card-slots': 'Slots covered',
      'lib-title': 'Library',
      'lib-sub-prefix': 'Total:',
      'lib-sub-mid': 'atoms · 9 slots · determinism score',
      'lib-legend': '≥80 high · 60–79 mid · <60 low',
      'atom-measured': 'Adherence {a}% · Baseline {b}% · Lift +{l}pp',
      'lib-search-ph': 'Search terms (EN/中文)',
      'lib-all': 'All',
      'lib-no-result': 'No matching terms',
      'ctx-model': 'Target model',
      'ctx-model-any': 'Any (generic)',
      'ctx-scene': 'Scene type',
      'ctx-scene-any': 'Any',
      'ctx-note': 'Suggestions & chips re-ranked by measured data (20 atoms · 3 models · 6 scene types; unmeasured atoms marked "no benchmark")',
      'btn-evidence': '🎯 Measured picks',
      'rec-toast': 'Filled {n} empty slot(s) from measured data ✓',
      'rec-none': 'No fillable empty slots (full or all conflicting)',
      'rec-whiteout': 'measured no-op',
      'rec-scene-dead': 'dead in this scene',
      'rec-scene-fit': '+{l}',
      'rec-strong': 'strong switch',
      'rec-split': 'split {d}',
      'rec-heuristic': 'no benchmark',
      'rec-conflict': 'conflict',
      'consent-title': 'Atlas collects limited, pseudonymized usage stats to improve CHECK — never your prompt text.',
      'consent-allow': 'Allow anonymous stats',
      'consent-local': 'Local only',
      'consent-note': 'Change anytime via the footer or the privacy page',
      'footer-stats': '📊 Stats',
      'footer-privacy': '🔒 Privacy',
      'invalid-title': '⚠ Measured no-effect words',
      'invalid-why-model': 'low measured score on this model',
      'invalid-why-scene': 'no measured effect in this scene type',
      'invalid-why-whiteout': 'measured no-op',
      'invalid-why-low': 'measured low score',
      'btn-share-card': '🖼️ Share card',
      'btn-share-card-img': '🖼️ Share card image',
      footer: 'Visual Prompt Atlas · local prototype · data source core.json (edit then run build.ps1 to sync) · image/video API hooks reserved'
    }
  };

  function detectLang() {
    try {
      var saved = localStorage.getItem('prompt-atlas-lang');
      if (saved === 'zh' || saved === 'en') return saved;
    } catch (e) { /* ignore */ }
    var nav = (navigator.language || 'en').toLowerCase();
    return nav.indexOf('zh') === 0 ? 'zh' : 'en';
  }
  var lang = detectLang();

  function t(key) {
    if (I18N[lang] && I18N[lang][key] !== undefined) return I18N[lang][key];
    if (I18N.zh[key] !== undefined) return I18N.zh[key];
    return key;
  }
  function term(o) { return (o && o[lang]) ? o[lang] : (o && o.zh); }
  function atomName(a) { return term({ zh: a.zh, en: a.en }); }
  function slotName(s) { return term({ zh: s.zh, en: s.en }); }
  function slotDesc(s) { return term({ zh: s.desc, en: s.descEn }); }

  /* ---------------- dom helpers ---------------- */
  function $(id) { return document.getElementById(id); }
  function el(tag, cls, html) {
    var n = document.createElement(tag);
    if (cls) n.className = cls;
    if (html !== undefined) n.innerHTML = html;
    return n;
  }
  function readScore(a) { return (a.score && typeof a.score === 'object') ? a.score.value : a.score; }
  function scoreClass(s) { return s >= 80 ? 'high' : (s >= 60 ? 'mid' : 'low'); }
  function scoreBadgeHtml(x) {
    var s = (typeof x === 'object' && x !== null) ? readScore(x) : x;
    return '<span class="score ' + scoreClass(s) + '">' + s + '</span>';
  }

  /* ---------------- evidence-aware recommendation (rec-data.js) ---------------- */
  function modelShort(id) {
    if (REC && REC.models) {
      for (var i = 0; i < REC.models.length; i++) if (REC.models[i].id === id) return REC.models[i].short;
    }
    return id;
  }
  function sceneLabel(sc) {
    if (!REC || !REC.scenes) return sc;
    for (var i = 0; i < REC.scenes.length; i++) if (REC.scenes[i].id === sc) return lang === 'zh' ? REC.scenes[i].zh + ' ' + REC.scenes[i].en : REC.scenes[i].en;
    return sc;
  }
  /* compact reason badges for one recommendation candidate (max 2, danger first) */
  function recBadgeHtml(cand) {
    var rs = cand.reasons || [];
    var byType = {};
    rs.forEach(function (r) { byType[r.type] = r; });
    var out = '', shown = 0;
    function span(cls, text, title) {
      return '<span class="rec-b ' + cls + '"' + (title ? ' title="' + escapeHtml(title) + '"' : '') + '>' + escapeHtml(text) + '</span>';
    }
    if (byType['model-mismatch']) { out += span('bad', modelShort(byType['model-mismatch'].model) + ' ' + byType['model-mismatch'].value + ' ⚠'); shown++; }
    if (byType['scene-dead'] && shown < 2) { out += span('bad', t('rec-scene-dead'), 'lift ' + byType['scene-dead'].lift + 'pp'); shown++; }
    if (byType.whiteout && shown < 2) { out += span('bad', t('rec-whiteout')); shown++; }
    if (cand.conflict && shown < 2) { out += span('bad', t('rec-conflict')); shown++; }
    if (byType['model-fit'] && shown < 2) { out += span('good', modelShort(byType['model-fit'].model) + ' ' + byType['model-fit'].value); shown++; }
    if (byType['scene-fit'] && shown < 2) { out += span('good', t('rec-scene-fit').replace('{l}', byType['scene-fit'].lift), 'lift +' + byType['scene-fit'].lift + 'pp'); shown++; }
    if (byType['strong-switch'] && shown < 2) { out += span('ok', t('rec-strong')); shown++; }
    if (byType['family-split'] && shown < 2 && !byType['model-fit'] && !byType['model-mismatch']) { out += span('warn', t('rec-split').replace('{d}', byType['family-split'].spread)); shown++; }
    if (byType['heuristic-fallback'] && shown < 2) { out += span('none', t('rec-heuristic')); shown++; }
    return out;
  }

  var toastTimer = null;
  function toast(msg, isErr) {
    var t = $('toast');
    if (!t) { t = el('div', 'toast'); t.id = 'toast'; document.body.appendChild(t); }
    t.textContent = msg;
    t.className = 'toast show' + (isErr ? ' err' : '');
    clearTimeout(toastTimer);
    toastTimer = setTimeout(function () { t.className = 'toast'; }, 2200);
  }
  function copyText(text) {
    function fallback() {
      try {
        var ta = document.createElement('textarea');
        ta.value = text;
        ta.style.position = 'fixed';
        ta.style.opacity = '0';
        document.body.appendChild(ta);
        ta.select();
        var ok = document.execCommand('copy');
        document.body.removeChild(ta);
        toast(ok ? t('copy-ok') : t('copy-fail'), !ok);
      } catch (e) { toast(t('copy-fail'), true); }
    }
    if (navigator.clipboard && navigator.clipboard.writeText) {
      navigator.clipboard.writeText(text).then(function () { toast(t('copy-ok')); }, fallback);
    } else { fallback(); }
  }

  /* ---------------- static i18n & tabs ---------------- */
  function applyStatic() {
    var nodes = document.querySelectorAll('[data-i18n]');
    for (var i = 0; i < nodes.length; i++) {
      var key = nodes[i].getAttribute('data-i18n');
      var val = t(key);
      if (val) nodes[i].textContent = val;
    }
    var phs = document.querySelectorAll('[data-i18n-ph]');
    for (var j = 0; j < phs.length; j++) {
      phs[j].setAttribute('placeholder', t(phs[j].getAttribute('data-i18n-ph')));
    }
    document.documentElement.lang = lang === 'zh' ? 'zh-CN' : 'en';
    var toggle = $('lang-toggle');
    if (toggle) toggle.textContent = lang === 'zh' ? '🌐 EN' : '🌐 中文';
  }

  function switchTab(name) {
    var buttons = document.querySelectorAll('#tabs button');
    for (var i = 0; i < buttons.length; i++) {
      buttons[i].className = buttons[i].getAttribute('data-tab') === name ? 'active' : '';
    }
    var views = document.querySelectorAll('.view');
    for (var j = 0; j < views.length; j++) {
      views[j].className = views[j].id === 'view-' + name ? 'view active' : 'view';
    }
  }

  /* ================= Prompt Checker / 体检仪 ================= */
  var lastAnalysis = null;
  var checkMode = 'video';
  var checkCtx = { model: '', scene: '' }; // evidence-aware context (rec-data.js)
  var lastReportData = null; // {r, invalidList} for the share card
  var EXAMPLES = {
    good: 'a young woman walking in the rain, golden hour, tracking shot, close-up, symmetrical composition, teal and orange, anime style, serene, rainy night, shallow depth of field, slow motion',
    bad: 'a girl in a city, cinematic'
  };

  function escapeHtml(s) {
    return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;');
  }
  function levelLabel(l) { return t('level-' + l); }

  function shareText(r) {
    var lines = [];
    lines.push('【' + t('checker-title') + '】' + t('profile-title'));
    lines.push(t('dim-reliability') + '：' + (r.reliability === null ? '—' : r.reliability + '/100'));
    lines.push(t('dim-coverage') + '：' + r.covered.length + '/' + r.applicable.length + '（' + (r.covered.length ? r.covered.map(function (s) { return slotName(s); }).join('、') : '—') + '）');
    lines.push(t('dim-consistency') + '：' + r.consistency + '/100');
    lines.push(t('dim-freedom') + '：' + r.freedom + '/' + r.applicable.length + (r.missing.length ? '（' + r.missing.map(function (s) { return slotName(s); }).join('、') + '）' : ''));
    lines.push(t('level-label') + '：' + levelLabel(r.controlLevel));
    if (r.notApplicable.length) lines.push('➖ ' + t('na-label') + '：' + r.notApplicable.map(function (s) { return slotName(s); }).join('、'));
    if (r.hardConflicts.length) lines.push('🚫 ' + t('sec-conflict') + '：' + r.hardConflicts.map(function (p) { return atomName(p.a) + ' ↔ ' + atomName(p.b); }).join('；'));
    if (r.tensions.length) lines.push('⚠️ ' + t('sec-tension') + '：' + r.tensions.map(function (p) { return atomName(p.a) + ' ↔ ' + atomName(p.b); }).join('；'));
    if (r.modalityMismatches.length) lines.push('⚠️ ' + t('sec-mismatch-title') + '：' + r.modalityMismatches.map(atomName).join('、'));
    if (r.uncertain.length) lines.push('⚠️ ' + t('uncertain-title') + '：' + r.uncertain.map(atomName).join('、'));
    lines.push('—— ' + t('brand') + ' Visual Prompt Atlas');
    return lines.join('\n');
  }

  function renderReport(r) {
    var box = $('checker-report');
    var pct = Math.round(r.coverage * 100);
    // measured-dead words found in this prompt (P0-005)
    var invalidList = (REC && LIB && LIB.invalidWords) ? LIB.invalidWords(REC, r.found, checkCtx.model || null, checkCtx.scene || null) : [];
    var html = '';
    if (invalidList.length) {
      html += '<div class="invalid-alert"><div class="invalid-title">' + t('invalid-title') + ' ' + invalidList.length + '</div>';
      invalidList.forEach(function (x) {
        var why = x.reasons.map(function (rr) {
          if (rr.type === 'model-mismatch') return t('invalid-why-model') + ' ' + rr.value;
          if (rr.type === 'scene-dead') return t('invalid-why-scene');
          if (rr.type === 'whiteout') return t('invalid-why-whiteout');
          if (rr.type === 'low-score') return t('invalid-why-low') + ' ' + rr.value;
          return null;
        }).filter(Boolean).join(' · ');
        html += '<div class="invalid-item"><b>' + atomName(x.atom) + '</b> <span class="chip-en">' + x.atom.en + '</span> <span class="score low">' + readScore(x.atom) + '</span> <span class="invalid-why">' + why + '</span></div>';
      });
      html += '</div>';
    }
    html += '<div class="rep-head">';
    html += '<div class="rep-score" style="--p:' + (r.reliability === null ? 0 : r.reliability) + '"><span class="score-num">' + (r.reliability === null ? '—' : r.reliability) + '</span><span class="score-max">/100</span></div>';
    html += '<div class="rep-meta">';
    html += '<div class="rep-level level-' + r.controlLevel + '">' + levelLabel(r.controlLevel) + '</div>';
    html += '<div class="rep-cov"><span>' + t('dim-coverage') + '</span><div class="bar"><div class="bar-fill" style="width:' + pct + '%"></div></div><b>' + r.covered.length + '/' + r.applicable.length + '</b></div>';
    html += '<div class="rep-cov"><span>' + t('dim-consistency') + '</span><div class="bar"><div class="bar-fill" style="width:' + r.consistency + '%"></div></div><b>' + r.consistency + '</b></div>';
    html += '<div class="rep-cov"><span>' + t('dim-freedom') + '</span><div class="bar"><div class="bar-fill" style="width:' + Math.round(r.freedom / Math.max(1, r.applicable.length) * 100) + '%"></div></div><b>' + r.freedom + '/' + r.applicable.length + '</b></div>';
    var counts = [];
    counts.push(t('count-macro') + ' ' + r.macroCount);
    counts.push(t('sec-conflict') + ' ' + r.hardConflicts.length);
    counts.push(t('sec-tension') + ' ' + r.tensions.length);
    counts.push(t('sec-redundant') + ' ' + r.redundants.length);
    html += '<div class="rep-counts">' + counts.join(' · ') + '</div>';
    if (r.evidence && r.evidence.total > 0) {
      html += '<div class="rep-ev">' + t('ev-note').replace('{b}', r.evidence.benchmarked).replace('{t}', r.evidence.total).replace('{f}', r.evidence.confidenceFloor) + '</div>';
    }
    if (r.maybeCount > 0) {
      html += '<div class="rep-maybe-note">' + t('opt-note-short').replace('{n}', r.maybeCount) + '</div>';
    }
    if (r.notApplicable.length > 0) {
      html += '<div class="rep-na-note">' + t('na-note').replace('{n}', r.applicable.length) + (r.timeIrrelevant ? ' · ' + t('time-irrelevant-note') : '') + '</div>';
    }
    // evidence-aware context: re-rank missing-slot suggestions by measured data
    var recMap = null;
    if (REC && LIB && LIB.recommendAtoms && (checkCtx.model || checkCtx.scene)) {
      var picksFound = {};
      r.found.forEach(function (a) { if (a.type !== 'macro') picksFound[a.slot] = a.id; });
      var recs = LIB.recommendAtoms(ATLAS, REC, { mode: checkMode, model: checkCtx.model || null, scene: checkCtx.scene || null, picks: picksFound });
      recMap = {};
      recs.slots.forEach(function (s) { recMap[s.slot.id] = s.candidates; });
      html += '<div class="rep-ev rec-active">🎯 ' + t('ctx-note') + '</div>';
    }
    html += '</div></div>';

    if (r.modalityMismatches.length) {
      html += '<div class="rep-uncertain mismatch"><div class="rep-unc-title">' + t('sec-mismatch-title') + '</div><div class="rep-unc-desc">' + t('sec-mismatch-desc') + '</div>';
      r.modalityMismatches.forEach(function (a) {
        html += '<span class="chip low-chip">' + atomName(a) + ' <span class="chip-en">' + a.en + '</span></span>';
      });
      html += '</div>';
    }
    if (r.hardConflicts.length) {
      html += '<div class="rep-uncertain conflict-sec"><div class="rep-unc-title">🚫 ' + t('sec-conflict') + '</div>';
      r.hardConflicts.forEach(function (p) {
        html += '<span class="chip conflict-chip">' + atomName(p.a) + ' ↔ ' + atomName(p.b) + '</span>';
      });
      html += '</div>';
    }
    if (r.tensions.length) {
      html += '<div class="rep-uncertain tension-sec"><div class="rep-unc-title">' + t('sec-tension') + '</div><div class="rep-unc-desc">' + t('sec-tension-desc') + '</div>';
      r.tensions.forEach(function (p) {
        html += '<span class="chip">' + atomName(p.a) + ' ↔ ' + atomName(p.b) + '</span>';
      });
      html += '</div>';
    }
    if (r.redundants.length) {
      html += '<div class="rep-uncertain tension-sec"><div class="rep-unc-title">' + t('sec-redundant') + '</div><div class="rep-unc-desc">' + t('sec-redundant-desc') + '</div>';
      r.redundants.forEach(function (p) {
        html += '<span class="chip">' + atomName(p.a) + ' ⟸ ' + atomName(p.b) + '</span>';
      });
      html += '</div>';
    }

    html += '<div class="rep-slots">';
    SLOTS.forEach(function (s) {
      var atoms = r.perSlot[s.id];
      var isNA = false;
      for (var na = 0; na < r.notApplicable.length; na++) {
        if (r.notApplicable[na].id === s.id) { isNA = true; break; }
      }
      if (atoms.length) {
        html += '<div class="rep-slot ok"><div class="rep-slot-name">' + slotName(s) + '</div><div class="rep-slot-body">';
        atoms.forEach(function (a) {
          html += '<span class="chip found" data-evidence-atom="' + a.id + '"><b>' + atomName(a) + '</b><span class="chip-en">' + a.en + '</span>' + scoreBadgeHtml(a) + (a.type === 'macro' ? '<span class="macro-mini">M</span>' : '') + '</span>';
        });
        var implied = r.impliedBySlot[s.id] || [];
        implied.forEach(function (a) {
          html += '<span class="chip implied" title="' + t('implied-tip') + '">⇐ ' + atomName(a) + ' <span class="chip-en">' + a.en + '</span></span>';
        });
        html += '</div></div>';
      } else if (isNA) {
        html += '<div class="rep-slot na"><div class="rep-slot-name">' + slotName(s) + '</div><div class="rep-slot-body">';
        html += '<span class="na-tag">' + t('na-tag') + '</span>';
        html += '</div></div>';
      } else {
        var detail = null;
        for (var k = 0; k < r.missingDetail.length; k++) {
          if (r.missingDetail[k].slot.id === s.id) { detail = r.missingDetail[k]; break; }
        }
        var isMaybe = detail && detail.maybe;
        html += '<div class="rep-slot ' + (isMaybe ? 'maybe' : 'miss') + '"><div class="rep-slot-name">' + slotName(s) + '</div><div class="rep-slot-body">';
        html += '<span class="miss-tag">' + (isMaybe ? t('suggest-maybe') : t('missing-label')) + '</span>';
        if (detail) {
          var suggList = detail.suggs;
          if (recMap && recMap[s.id]) {
            suggList = recMap[s.id].filter(function (c) { return !c.conflict; }).slice(0, 3)
              .map(function (c) { return { atom: c.atom, conflict: false, badge: recBadgeHtml(c), dead: c.tier === 0 }; });
          }
          suggList.forEach(function (x) {
            var a = x.atom;
            if (x.conflict) {
              html += '<span class="chip conflict-chip" title="' + t('conflict-tip') + '">' + atomName(a) + ' <span class="chip-en">' + a.en + '</span>' + scoreBadgeHtml(a) + '<span class="conflict-badge">' + t('suggest-conflict') + '</span></span>';
            } else {
              html += '<span class="chip sugg' + (x.dead ? ' rec-dead' : '') + '" data-add="' + escapeHtml(a.en) + '" data-evidence-atom="' + a.id + '">+ ' + atomName(a) + ' <span class="chip-en">' + a.en + '</span>' + (x.badge || '') + '</span>';
            }
          });
          if (!suggList.length) {
            html += '<span class="miss-tag">' + t('opt-none') + '</span>';
          }
        }
        html += '</div></div>';
      }
    });
    html += '</div>';
    if (r.uncertain.length) {
      html += '<div class="rep-uncertain"><div class="rep-unc-title">' + t('uncertain-title') + '</div><div class="rep-unc-desc">' + t('uncertain-desc') + '</div>';
      r.uncertain.forEach(function (a) {
        html += '<span class="chip low-chip">' + atomName(a) + ' <span class="chip-en">' + a.en + '</span>' + scoreBadgeHtml(a) + '</span>';
      });
      html += '</div>';
    }
    html += '<div class="btn-row"><button id="share-report" class="btn primary">' + t('share-btn') + '</button><button id="opt-report" class="btn">' + t('opt-btn') + '</button><button id="share-card-btn" class="btn ghost">' + t('btn-share-card') + '</button></div>';
    box.innerHTML = html;
    lastReportData = { r: r, invalidList: invalidList };

    trk('check_completed', {
      foundAtoms: r.found.filter(function (a) { return a.type !== 'macro'; }).map(function (a) { return a.id; }),
      controlLevel: r.controlLevel,
      coverage: r.coverage,
      invalidCount: invalidList.length
    });

    // evidence_viewed: first time an evidence badge scrolls into view (consent-gated)
    if (AN && AN.enabled() && typeof IntersectionObserver === 'function') {
      var seenEv = {};
      var io = new IntersectionObserver(function (entries) {
        entries.forEach(function (en) {
          if (!en.isIntersecting) return;
          var id = en.target.getAttribute('data-evidence-atom');
          if (id && !seenEv[id]) { seenEv[id] = true; trk('evidence_viewed', { atomId: id, kind: 'badge' }); }
          io.unobserve(en.target);
        });
      }, { root: box });
      var evBadges = box.querySelectorAll('[data-evidence-atom]');
      for (var ei = 0; ei < evBadges.length; ei++) io.observe(evBadges[ei]);
    }

    var suggs = box.querySelectorAll('.chip.sugg');
    for (var i = 0; i < suggs.length; i++) {
      suggs[i].addEventListener('click', function () {
        var add = this.getAttribute('data-add');
        trk('recommendation_applied', { atomId: this.getAttribute('data-evidence-atom') || undefined, source: 'sugg' });
        var ta = $('checker-input');
        ta.value = (ta.value.trim() ? ta.value.replace(/\s*$/, '') + ', ' : '') + add;
        runCheck();
      });
    }
    $('share-report').addEventListener('click', function () { copyText(shareText(r)); trk('share_created', { kind: 'check_report' }); });
    $('share-card-btn').addEventListener('click', function () {
      if (!window.AtlasShareCard || !lastReportData) return;
      var rr = lastReportData.r;
      var badges = [];
      rr.found.forEach(function (a) {
        if (a.type === 'macro' || !REC || !LIB || !LIB.evaluateAtomRec) return;
        var ev = LIB.evaluateAtomRec(REC, a, checkCtx.model || null, checkCtx.scene || null);
        if (!ev.rec) return;
        var bad = ev.tier === 0;
        if (!bad && ev.base < 70) return;
        badges.push({ name: a.zh, score: ev.base, kind: bad ? 'bad' : 'ok' });
      });
      var canvas = AtlasShareCard.reportCard({
        reliability: rr.reliability,
        covered: rr.covered.length,
        total: rr.applicable.length,
        consistency: rr.consistency,
        freedom: rr.freedom,
        badges: badges.slice(0, 10),
        invalidCount: lastReportData.invalidList.length
      });
      AtlasShareCard.download(canvas, 'atlas-check-report.png').then(function (ok) {
        if (ok) trk('share_created', { kind: 'check_report', score: rr.reliability == null ? undefined : rr.reliability });
      });
    });
    $('opt-report').addEventListener('click', function () {
      var existing = box.querySelector('.opt-block');
      if (existing) { existing.parentNode.removeChild(existing); return; }
      var opt = buildOptimized(r);
      var div = el('div', 'opt-block');
      div.innerHTML = renderOptimizedHtml(opt, r);
      var btnRow = box.querySelector('.btn-row');
      btnRow.parentNode.insertBefore(div, btnRow);
      if (div.scrollIntoView) div.scrollIntoView({ behavior: 'smooth', block: 'center' });
      var copyBtn = div.querySelector('[data-optcopy]');
      if (copyBtn) copyBtn.addEventListener('click', function () {
        copyText(optCopyText(opt, r));
        trk('export_clicked', { kind: 'optimized_prompt', atomsCount: opt.added.length });
      });
    });
  }

  function buildOptimized(r) {
    return LIB.buildOptimized(ATLAS, r);
  }

  function slotById(id) {
    for (var i = 0; i < SLOTS.length; i++) if (SLOTS[i].id === id) return SLOTS[i];
    return { id: id, zh: id, en: id, desc: '', descEn: '' };
  }

  function renderOptimizedHtml(opt, r) {
    var html = '';
    html += '<div class="opt-title">' + t('opt-title') + '</div>';
    if (opt.added.length === 0 && opt.skipped.length === 0) {
      html += '<div class="opt-complete">' + t('opt-complete') + '</div>';
    }
    html += '<div class="opt-en">' + escapeHtml(opt.en) + '</div>';
    var zhLines = [];
    r.covered.forEach(function (s) {
      var names = r.perSlot[s.id].map(atomName).join('、');
      var impliedNames = (r.impliedBySlot[s.id] || []).map(atomName).join('、');
      zhLines.push(slotName(s) + '：' + t('opt-covered') + ' ' + (names ? names : impliedNames));
    });
    opt.maybeSlots.forEach(function (id) { zhLines.push(slotName(slotById(id)) + '：' + t('opt-maybe-line')); });
    opt.added.forEach(function (a) { zhLines.push(slotName(slotById(a.slot)) + '：' + t('opt-add') + ' ' + atomName(a) + '（' + a.en + '）'); });
    opt.noSuggestion.forEach(function (id) { zhLines.push(slotName(slotById(id)) + '：' + t('opt-none')); });
    html += '<div class="opt-zh">' + zhLines.map(escapeHtml).join('<br>') + '</div>';
    opt.expansions.forEach(function (e) {
      html += '<div class="opt-expand">💡 ' + escapeHtml(t('opt-expand-label').replace('{macro}', atomName(e.macro))) + '：' + e.targets.map(function (a) { return atomName(a) + '（' + a.en + '）'; }).map(escapeHtml).join(' + ') + '</div>';
    });
    if (opt.maybeCount) html += '<div class="opt-note">' + t('opt-note').replace('{n}', opt.maybeCount) + '</div>';
    html += '<div class="opt-stats">' + t('opt-add') + '：' + opt.added.length + ' · ' + t('opt-skip') + '：' + opt.skipped.length + '</div>';
    if (opt.longPrefix) html += '<div class="opt-note">' + t('opt-prefix-note') + '</div>';
    html += '<button class="btn primary" data-optcopy="1">' + t('opt-copy') + '</button>';
    return html;
  }

  function optCopyText(opt, r) {
    var lines = [];
    lines.push('🎬 ' + t('opt-title'));
    lines.push('EN: ' + opt.en);
    lines.push(t('opt-zh-title') + '：');
    r.covered.forEach(function (s) {
      var names = r.perSlot[s.id].map(atomName).join('、');
      var impliedNames = (r.impliedBySlot[s.id] || []).map(atomName).join('、');
      lines.push('  ' + slotName(s) + '：' + t('opt-covered') + ' ' + (names ? names : impliedNames));
    });
    opt.maybeSlots.forEach(function (id) { lines.push('  ' + slotName(slotById(id)) + '：' + t('opt-maybe-line')); });
    opt.added.forEach(function (a) { lines.push('  ' + slotName(slotById(a.slot)) + '：' + t('opt-add') + ' ' + atomName(a) + '（' + a.en + '）'); });
    opt.noSuggestion.forEach(function (id) { lines.push('  ' + slotName(slotById(id)) + '：' + t('opt-none')); });
    opt.expansions.forEach(function (e) {
      lines.push('💡 ' + t('opt-expand-label').replace('{macro}', atomName(e.macro)) + '：' + e.targets.map(function (a) { return atomName(a) + '（' + a.en + '）'; }).join(' + '));
    });
    if (opt.maybeCount) lines.push(t('opt-note').replace('{n}', opt.maybeCount));
    if (opt.longPrefix) lines.push(t('opt-prefix-note'));
    lines.push('—— ' + t('brand') + ' Visual Prompt Atlas');
    return lines.join('\n');
  }

  function runCheck() {
    var text = $('checker-input').value.trim();
    if (!text) { toast(t('input-empty'), true); return; }
    trk('check_started', { mode: checkMode, model: checkCtx.model || undefined, scene: checkCtx.scene || undefined, promptLength: text.length });
    lastAnalysis = LIB.analyze(ATLAS, text, checkMode);
    renderReport(lastAnalysis);
  }

  /* ================= Recipe Card / 配方卡 ================= */
  var recipe = { subject: '', action: '', scene: '', picks: {} };
  var recipeMode = 'video';
  var recipeCtx = { model: '', scene: '' }; // evidence-aware context (rec-data.js)
  var SAMPLES = {
    zh: {
      subjects: ['一位年轻女子', '一只白猫', '一位老者', '一名宇航员', '一个旧机器人'],
      actions: ['在雨中行走', '静静站立', '缓缓转身', '奔跑追逐', '抬头仰望'],
      scenes: ['赛博朋克城市街头', '雪山之巅', '老上海弄堂', '废弃的火车站', '海边灯塔']
    },
    en: {
      subjects: ['a young woman', 'a white cat', 'an old man', 'an astronaut', 'a rusty robot'],
      actions: ['walking in the rain', 'standing still', 'turning around slowly', 'running and chasing', 'looking up at the sky'],
      scenes: ['a cyberpunk city street', 'a snowy mountain peak', 'an old Shanghai alley', 'an abandoned train station', 'a lighthouse by the sea']
    }
  };

  /* slot -> evidence-ranked candidates when a target model / scene type is set */
  function recipeRecMap() {
    if (!REC || !LIB || !LIB.recommendAtoms) return null;
    if (!recipeCtx.model && !recipeCtx.scene) return null;
    var recs = LIB.recommendAtoms(ATLAS, REC, { mode: recipeMode, model: recipeCtx.model || null, scene: recipeCtx.scene || null, picks: recipe.picks });
    var map = {};
    recs.slots.forEach(function (s) { map[s.slot.id] = s.candidates; });
    return map;
  }

  function renderPickers() {
    var box = $('slot-pickers');
    box.innerHTML = '';
    var recMap = recipeRecMap();
    SLOTS.forEach(function (s) {
      var wrap = el('div', 'picker');
      var head = el('div', 'picker-head');
      head.innerHTML = '<span class="picker-name">' + slotName(s) + '</span><span class="picker-desc">' + slotDesc(s) + '</span>';
      var chips = el('div', 'picker-chips');
      var list = (BY_SLOT[s.id] || []).filter(function (a) { return LIB ? LIB.atomAppliesToMode(a, recipeMode) : true; })
        .map(function (a) { return { atom: a, cand: null }; });
      if (recMap && recMap[s.id]) {
        // re-rank chips by measured tier (dead last); macros keep library order at the end
        var byId = {};
        list.forEach(function (it) { byId[it.atom.id] = it; });
        var ordered = [];
        recMap[s.id].forEach(function (c) {
          if (byId[c.atom.id]) { ordered.push({ atom: c.atom, cand: c }); byId[c.atom.id] = null; }
        });
        list.forEach(function (it) { if (byId[it.atom.id]) ordered.push(it); });
        list = ordered;
      }
      list.forEach(function (item) {
        var a = item.atom;
        var c = el('button', 'chip' + (recipe.picks[s.id] === a.id ? ' sel' : '') + (item.cand && item.cand.tier === 0 ? ' rec-dead' : ''));
        c.setAttribute('data-atom', a.id);
        c.innerHTML = atomName(a) + ' <span class="chip-en">' + a.en + '</span>' + scoreBadgeHtml(a) + (item.cand ? recBadgeHtml(item.cand) : '');
        c.addEventListener('click', function () {
          recipe.picks[s.id] = (recipe.picks[s.id] === a.id) ? null : a.id;
          renderPickers();
          renderPreview();
        });
        chips.appendChild(c);
      });
      wrap.appendChild(head);
      wrap.appendChild(chips);
      box.appendChild(wrap);
    });
  }

  /* fill empty slots with the best measured, non-conflicting candidate per slot */
  function evidencePick() {
    if (!REC || !LIB || !LIB.recommendAtoms) { toast(t('rec-none'), true); return; }
    var recs = LIB.recommendAtoms(ATLAS, REC, { mode: recipeMode, model: recipeCtx.model || null, scene: recipeCtx.scene || null, picks: recipe.picks });
    var picked = Object.keys(recipe.picks).map(function (sid) { return atomById(recipe.picks[sid]); }).filter(Boolean);
    var n = 0;
    recs.slots.forEach(function (s) {
      if (recipe.picks[s.slot.id]) return;
      var cands = s.candidates;
      for (var i = 0; i < cands.length; i++) {
        var c = cands[i];
        if (c.tier < 1) continue;
        var bad = c.conflict || picked.some(function (p) { return LIB.pairConflict(c.atom, p) || LIB.pairConflict(p, c.atom); });
        if (bad) continue;
        recipe.picks[s.slot.id] = c.atom.id;
        picked.push(c.atom);
        n++;
        break;
      }
    });
    if (!n) { toast(t('rec-none'), true); return; }
    renderPickers();
    renderPreview();
    toast(t('rec-toast').replace('{n}', n));
  }

  function atomById(id) {
    for (var i = 0; i < ATOMS.length; i++) if (ATOMS[i].id === id) return ATOMS[i];
    return null;
  }

  function pickedAtoms() {
    var out = [];
    SLOTS.forEach(function (s) {
      var a = recipe.picks[s.id] ? atomById(recipe.picks[s.id]) : null;
      if (a) out.push(a);
    });
    return out;
  }

  function assemble() {
    var rp = LIB.recipeProfile(ATLAS, { subject: recipe.subject, action: recipe.action, scene: recipe.scene, picks: recipe.picks, mode: recipeMode });
    var atoms = rp.atoms;
    var baseZh = recipe.subject + (recipe.action || '') + (recipe.scene ? '，' + recipe.scene : '');
    var partsZh = atoms.map(function (a) { return slotName(slotOf(a)) + '：' + a.zh; });
    var zh = (baseZh ? baseZh + '。' : '') + partsZh.join('，') + (partsZh.length ? '。' : '');
    return { en: rp.en || '—', zh: zh || '—', atoms: atoms, profile: rp.profile };
  }
  function profileLine(p) {
    if (!p) return '—';
    var line = t('cp-r') + ' ' + (p.reliability === null ? '—' : p.reliability) +
      ' · ' + t('cp-c') + ' ' + p.covered.length + '/' + p.applicable.length +
      ' · ' + t('cp-s') + ' ' + p.consistency +
      ' · ' + t('cp-f') + ' ' + p.freedom;
    if (p.evidence && p.evidence.total > 0) {
      line += ' · ' + t('ev-note').replace('{b}', p.evidence.benchmarked).replace('{t}', p.evidence.total).replace('{f}', p.evidence.confidenceFloor);
    }
    return line;
  }
  function slotOf(a) {
    for (var i = 0; i < SLOTS.length; i++) if (SLOTS[i].id === a.slot) return SLOTS[i];
    return { zh: a.slot, en: a.slot, desc: '', descEn: '' };
  }

  function cardText(a) {
    var lines = [];
    lines.push('🎬 ' + t('card-brand'));
    if (recipe.subject) lines.push(t('f-subject') + '：' + recipe.subject);
    if (recipe.action) lines.push(t('f-action') + '：' + recipe.action);
    if (recipe.scene) lines.push(t('f-scene') + '：' + recipe.scene);
    a.atoms.forEach(function (x) { lines.push(slotName(slotOf(x)) + '：' + atomName(x) + '（' + x.en + '）'); });
    lines.push('Control Profile · ' + profileLine(a.profile) + ' · ' + t('card-slots') + '：' + a.atoms.length + '/' + SLOTS.length);
    lines.push('—— ' + t('brand') + ' Visual Prompt Atlas');
    return lines.join('\n');
  }

  function gradClass() {
    var color = recipe.picks.color ? atomById(recipe.picks.color) : null;
    if (color) {
      var map = {
        'cyberpunk-palette': 'grad-cyberpunk', monochrome: 'grad-mono', pastel: 'grad-pastel',
        'high-sat': 'grad-vivid', desaturated: 'grad-desat', 'teal-orange': 'grad-teal'
      };
      if (map[color.id]) return map[color.id];
    }
    var time = recipe.picks.time ? atomById(recipe.picks.time) : null;
    if (time) {
      var tmap = { dawn: 'grad-dawn', dusk: 'grad-dusk', 'blue-hour': 'grad-blue-hour', night: 'grad-night', 'rainy-night': 'grad-rainy-night' };
      if (tmap[time.id]) return tmap[time.id];
    }
    return 'grad-default';
  }

  function renderPreview() {
    var box = $('card-preview');
    var a = assemble();
    var hasAny = recipe.subject || recipe.action || recipe.scene || a.atoms.length > 0;
    if (!hasAny) {
      box.innerHTML = '<div class="card-empty">' + t('card-empty') + '</div>';
    } else {
      var midMain = escapeHtml((recipe.subject ? recipe.subject + ' ' : '') + (recipe.action ? recipe.action : '') + (recipe.scene ? ' @ ' + recipe.scene : ''));
      var chipsHtml = a.atoms.map(function (x) { return '<span class="cc">' + atomName(x) + '</span>'; }).join('');
      box.innerHTML =
        '<div class="card-stage ' + gradClass() + '">' +
        '<div class="card-top"><span class="card-brand">' + t('card-brand') + '</span>' +
        '<span class="card-scorepill">R ' + (a.profile.reliability === null ? '—' : a.profile.reliability) + '</span></div>' +
        '<div class="card-mid"><div class="card-main">' + midMain +
        '<small>' + profileLine(a.profile) + ' · ' + t('card-slots') + ': ' + a.atoms.length + '/' + SLOTS.length + '</small></div>' +
        '<span class="card-img-note">' + t('card-img-note') + '</span></div>' +
        '<div class="card-chips">' + chipsHtml + '</div>' +
        '</div>' +
        '<div class="card-foot"><span>Control Profile</span><b>' + profileLine(a.profile) + '</b></div>';
    }
    $('prompt-en').textContent = a.en;
    $('prompt-zh').textContent = a.zh;
    $('prompt-card').textContent = cardText(a);
  }

  function randomRecipe() {
    var s = SAMPLES[lang] || SAMPLES.zh;
    function pick(arr) { return arr[Math.floor(Math.random() * arr.length)]; }
    recipe.subject = pick(s.subjects);
    recipe.action = pick(s.actions);
    recipe.scene = pick(s.scenes);
    recipe.picks = {};
    SLOTS.forEach(function (slot) {
      var list = (BY_SLOT[slot.id] || []).filter(function (a) { return LIB ? LIB.atomAppliesToMode(a, recipeMode) : true; });
      if (list.length) recipe.picks[slot.id] = list[Math.floor(Math.random() * list.length)].id;
    });
    $('recipe-subject').value = recipe.subject;
    $('recipe-action').value = recipe.action;
    $('recipe-ctx-scene').value = recipe.scene;
    renderPickers();
    renderPreview();
  }
  function resetRecipe() {
    recipe = { subject: '', action: '', scene: '', picks: {} };
    $('recipe-subject').value = '';
    $('recipe-action').value = '';
    $('recipe-ctx-scene').value = '';
    renderPickers();
    renderPreview();
  }

  /* ---------- recipe share link (URL hash, static-site friendly) ---------- */
  function buildShareUrl() {
    var payload = { v: 1, s: recipe.subject, a: recipe.action, sc: recipe.scene, p: recipe.picks, m: recipeMode };
    var b64 = btoa(unescape(encodeURIComponent(JSON.stringify(payload))));
    return location.origin + location.pathname + '#r=' + b64.replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
  }
  function loadFromHash() {
    if (location.hash.indexOf('#r=') !== 0) return false;
    try {
      var b64 = location.hash.slice(3).replace(/-/g, '+').replace(/_/g, '/');
      while (b64.length % 4) b64 += '=';
      var payload = JSON.parse(decodeURIComponent(escape(atob(b64))));
      if (!payload || typeof payload !== 'object') return false;
      recipe.subject = String(payload.s || '').slice(0, 300);
      recipe.action = String(payload.a || '').slice(0, 300);
      recipe.scene = String(payload.sc || '').slice(0, 300);
      recipe.picks = {};
      var picks = payload.p || {};
      Object.keys(picks).forEach(function (sid) {
        if (atomById(picks[sid])) recipe.picks[sid] = picks[sid]; // whitelist: dictionary ids only
      });
      if (payload.m === 'image' || payload.m === 'video') recipeMode = payload.m;
      $('recipe-subject').value = recipe.subject;
      $('recipe-action').value = recipe.action;
      $('recipe-ctx-scene').value = recipe.scene;
      return true;
    } catch (e) { return false; }
  }

  /* ================= Library / 词库 ================= */
  var libState = { slot: 'all', q: '' };

  function renderLibrary() {
    $('lib-count').textContent = String(ATOMS.length);
    var bar = $('lib-slots');
    bar.innerHTML = '';
    var allBtn = el('button', libState.slot === 'all' ? 'active' : '', t('lib-all'));
    allBtn.addEventListener('click', function () { libState.slot = 'all'; renderLibrary(); });
    bar.appendChild(allBtn);
    SLOTS.forEach(function (s) {
      var b = el('button', libState.slot === s.id ? 'active' : '', slotName(s));
      b.addEventListener('click', function () { libState.slot = s.id; renderLibrary(); });
      bar.appendChild(b);
    });

    var grid = $('lib-grid');
    grid.innerHTML = '';
    var q = libState.q.trim().toLowerCase();
    var list = ATOMS.filter(function (a) {
      if (libState.slot !== 'all' && a.slot !== libState.slot) return false;
      if (!q) return true;
      return a.zh.toLowerCase().indexOf(q) !== -1 || a.en.toLowerCase().indexOf(q) !== -1 || a.desc.indexOf(q) !== -1 || (a.descEn && a.descEn.toLowerCase().indexOf(q) !== -1);
    });
    if (!list.length) {
      grid.appendChild(el('div', 'lib-empty', t('lib-no-result')));
      return;
    }
    list.forEach(function (a) {
      var card = el('div', 'atom-card');
      var meta = '';
      if (a.type === 'macro') meta += '<span class="macro-badge">' + t('macro-badge') + '</span>';
      if (a.score && a.score.status === 'benchmarked') meta += '<span class="status-badge bench">' + t('bench-badge') + '</span>';
      else meta += '<span class="status-badge est">' + t('est-badge') + '</span>';
      var expandHtml = '';
      if (a.relations && a.relations.expandsTo && a.relations.expandsTo.length) {
        var names = a.relations.expandsTo.map(function (id) {
          var t = LIB ? LIB.atomById(ATLAS, id) : null;
          return t ? term({ zh: t.zh, en: t.en }) : id;
        }).join('、');
        expandHtml = '<div class="atom-meta">' + t('macro-expands') + '：' + names + '</div>';
      }
      var measuredHtml = '';
      if (a.score && a.score.status === 'benchmarked' && a.score.measured) {
        var mm = a.score.measured;
        var evidenceStats = a.score.sampleSize
          ? ' · ' + Math.round(a.score.sampleSize / 2) + ' 对 · ' + (a.score.models ? a.score.models.length : 0) + ' 家族'
          : '';
        measuredHtml = '<div class="atom-measured">' +
          t('atom-measured').replace('{a}', mm.adherence).replace('{b}', mm.baseline).replace('{l}', mm.lift) +
          evidenceStats + '</div>';
      }
      var byModelHtml = '';
      if (a.score && a.score.byModel) {
        var SHORT = { 'doubao-seedream-4-0-250828': 'Seedream 4.0', 'doubao-seedream-4-5-251128': 'Seedream 4.5', 'zhipu-cogview-4': 'CogView-4' };
        var parts = Object.keys(a.score.byModel).map(function (m) {
          return (SHORT[m] || m) + ' ' + a.score.byModel[m];
        });
        byModelHtml = '<div class="atom-bymodel">' + parts.join(' · ') + '</div>';
      }
      var evidenceHtml = '';
      if (a.evidence && a.evidence.control && a.evidence.treatment) {
        var modelLabel = a.evidence.model.indexOf('zhipu') === 0 ? 'CogView-4'
          : (a.evidence.model.indexOf('4-0') !== -1 ? 'Seedream 4.0' : 'Seedream 4.5');
        evidenceHtml = '<div class="atom-evidence">' +
          '<a href="' + a.evidence.control + '" target="_blank" rel="noopener" title="' + t('evidence-without') + '">' +
          '<img src="' + a.evidence.control + '" alt="control" loading="lazy"><span>' + t('evidence-without') + '</span></a>' +
          '<a href="' + a.evidence.treatment + '" target="_blank" rel="noopener" title="' + t('evidence-with') + '">' +
          '<img src="' + a.evidence.treatment + '" alt="treatment" loading="lazy"><span>' + t('evidence-with') + '</span></a>' +
          '<em>' + t('evidence-note').replace('{model}', modelLabel).replace('{scene}', a.evidence.scene)
            .replace('{c}', a.evidence.judged ? a.evidence.judged.control : '-').replace('{t}', a.evidence.judged ? a.evidence.judged.treatment : '-') + '</em>' +
          '</div>';
      }
      card.innerHTML =
        '<div class="atom-head"><span class="atom-zh"><a class="atom-page-link" href="atoms/' + encodeURIComponent(a.id) + '/">' + a.zh + '</a>' + meta + '</span>' + scoreBadgeHtml(a) + '</div>' +
        '<div class="atom-en">' + a.en + '</div>' +
        '<div class="atom-desc">' + term({ zh: a.desc, en: a.descEn }) + '</div>' +
        expandHtml +
        measuredHtml +
        byModelHtml +
        evidenceHtml +
        '<div class="atom-example">' + a.example + '</div>';
      grid.appendChild(card);
    });
  }

  /* ================= consent UI (P0-003) ================= */
  function renderConsentUI() {
    if (!AN) return;
    var state = AN.consentState();
    var banner = document.getElementById('consent-banner');
    if (!state) {
      if (!banner) {
        var b = el('div', 'consent-banner');
        b.id = 'consent-banner';
        b.innerHTML =
          '<div class="consent-text">' + t('consent-title') + ' <a href="privacy.html">' + t('footer-privacy') + '</a></div>' +
          '<div class="consent-btns"><button id="consent-yes" class="btn primary">' + t('consent-allow') + '</button>' +
          '<button id="consent-no" class="btn ghost">' + t('consent-local') + '</button></div>' +
          '<div class="consent-note">' + t('consent-note') + '</div>';
        document.body.appendChild(b);
        $('consent-yes').addEventListener('click', function () {
          AN.setConsent('granted');
          try { AN.pageView(location.pathname, document.referrer, lang); } catch (e) { /* ignore */ }
          renderConsentUI();
        });
        $('consent-no').addEventListener('click', function () { AN.setConsent('local'); renderConsentUI(); });
      }
    } else if (banner) { banner.parentNode.removeChild(banner); }
    var footer = document.querySelector('footer');
    if (footer && !document.getElementById('footer-stats-btn')) {
      var wrap = el('div', 'footer-controls');
      wrap.innerHTML = '<button class="footer-link" id="footer-stats-btn"></button> · <a class="footer-link" href="privacy.html">' + t('footer-privacy') + '</a>';
      footer.appendChild(wrap);
      $('footer-stats-btn').addEventListener('click', function () {
        AN.setConsent(AN.consentState() === 'granted' ? 'local' : 'granted');
        renderConsentUI();
        toast(t(AN.consentState() === 'granted' ? 'consent-allow' : 'consent-local') + ' ✓');
      });
    }
    var statsBtn = $('footer-stats-btn');
    if (statsBtn) statsBtn.textContent = t('footer-stats') + '：' + (state === 'granted' ? 'ON' : 'OFF');
  }

  /* ================= global render & events ================= */
  function renderCtx() {
    if (!REC) return;
    function modelItems() {
      return REC.models.map(function (m) { return { value: m.id, label: m.short }; });
    }
    function sceneItems() {
      return REC.scenes.map(function (sc) { return { value: sc.id, label: lang === 'zh' ? sc.zh + ' ' + sc.en : sc.en }; });
    }
    function fill(sel, anyLabel, items, value) {
      if (!sel) return;
      var html = '<option value="">' + escapeHtml(anyLabel) + '</option>';
      items.forEach(function (it) { html += '<option value="' + escapeHtml(it.value) + '">' + escapeHtml(it.label) + '</option>'; });
      sel.innerHTML = html;
      sel.value = value || '';
    }
    fill($('check-ctx-model'), t('ctx-model-any'), modelItems(), checkCtx.model);
    fill($('check-ctx-scene'), t('ctx-scene-any'), sceneItems(), checkCtx.scene);
    fill($('recipe-ctx-model'), t('ctx-model-any'), modelItems(), recipeCtx.model);
    fill($('recipe-ctx-scene'), t('ctx-scene-any'), sceneItems(), recipeCtx.scene);
  }

  function renderAll() {
    applyStatic();
    renderCtx();
    if (lastAnalysis) renderReport(lastAnalysis);
    renderPickers();
    renderPreview();
    renderLibrary();
    renderConsentUI();
  }

  function wire() {
    $('lang-toggle').addEventListener('click', function () {
      lang = lang === 'zh' ? 'en' : 'zh';
      try { localStorage.setItem('prompt-atlas-lang', lang); } catch (e) { /* ignore */ }
      renderAll();
    });
    var tabs = document.querySelectorAll('#tabs button');
    for (var i = 0; i < tabs.length; i++) {
      tabs[i].addEventListener('click', function () { switchTab(this.getAttribute('data-tab')); });
    }
    $('checker-run').addEventListener('click', runCheck);
    var modeImage = $('mode-image');
    var modeVideo = $('mode-video');
    function setMode(mode) {
      checkMode = mode;
      if (modeImage) modeImage.className = 'mode-btn' + (mode === 'image' ? ' active' : '');
      if (modeVideo) modeVideo.className = 'mode-btn' + (mode === 'video' ? ' active' : '');
      if (lastAnalysis) runCheck();
    }
    if (modeImage) modeImage.addEventListener('click', function () { setMode('image'); });
    if (modeVideo) modeVideo.addEventListener('click', function () { setMode('video'); });
    $('checker-clear').addEventListener('click', function () {
      $('checker-input').value = '';
      lastAnalysis = null;
      $('checker-report').innerHTML = '<div class="report-empty" data-i18n="report-empty">' + t('report-empty') + '</div>';
    });
    $('checker-example').addEventListener('click', function () { $('checker-input').value = EXAMPLES.good; runCheck(); });
    $('checker-example-bad').addEventListener('click', function () { $('checker-input').value = EXAMPLES.bad; runCheck(); });
    $('recipe-random').addEventListener('click', randomRecipe);
    $('recipe-share').addEventListener('click', function () {
      history.replaceState(null, '', buildShareUrl());
      copyText(buildShareUrl());
      trk('share_created', { kind: 'recipe_card' });
    });
    var recipeCardBtn = $('recipe-share-card');
    if (recipeCardBtn) recipeCardBtn.addEventListener('click', function () {
      if (!window.AtlasShareCard) return;
      var a = assemble();
      var slots = a.atoms.map(function (x) { return { zh: x.zh, score: readScore(x) }; });
      var canvas = AtlasShareCard.recipeCard({
        title: recipe.subject ? String(recipe.subject).slice(0, 24) : '视觉配方卡',
        slots: slots,
        reliability: a.profile.reliability
      });
      AtlasShareCard.download(canvas, 'atlas-recipe-card.png').then(function (ok) {
        if (ok) trk('share_created', { kind: 'recipe_card', score: a.profile.reliability == null ? undefined : a.profile.reliability });
      });
    });
    var rModeImage = $('recipe-mode-image');
    var rModeVideo = $('recipe-mode-video');
    function setRecipeMode(mode) {
      recipeMode = mode;
      if (rModeImage) rModeImage.className = 'mode-btn' + (mode === 'image' ? ' active' : '');
      if (rModeVideo) rModeVideo.className = 'mode-btn' + (mode === 'video' ? ' active' : '');
      recipe.picks = {};
      renderPickers();
      renderPreview();
    }
    if (rModeImage) rModeImage.addEventListener('click', function () { setRecipeMode('image'); });
    if (rModeVideo) rModeVideo.addEventListener('click', function () { setRecipeMode('video'); });
    $('recipe-reset').addEventListener('click', resetRecipe);
    ['recipe-subject', 'recipe-action', 'recipe-scene'].forEach(function (id) {
      $(id).addEventListener('input', function () {
        recipe[id.replace('recipe-', '')] = this.value;
        renderPreview();
      });
    });
    var copyBtns = document.querySelectorAll('[data-copy]');
    for (var j = 0; j < copyBtns.length; j++) {
      copyBtns[j].addEventListener('click', function () {
        var target = this.getAttribute('data-copy');
        copyText($(target).textContent);
        if (target === 'prompt-en' || target === 'prompt-zh' || target === 'prompt-card') trk('export_clicked', { kind: 'recipe' });
      });
    }
    $('lib-search').addEventListener('input', function () { libState.q = this.value; renderLibrary(); });

    /* evidence-aware context selects + measured-pick button */
    if (REC) {
      var cm = $('check-ctx-model'), cs = $('check-ctx-scene');
      if (cm) cm.addEventListener('change', function () { checkCtx.model = cm.value; if (lastAnalysis) runCheck(); });
      if (cs) cs.addEventListener('change', function () { checkCtx.scene = cs.value; if (lastAnalysis) runCheck(); });
      var rm = $('recipe-ctx-model'), rs2 = $('recipe-ctx-scene');
      if (rm) rm.addEventListener('change', function () { recipeCtx.model = rm.value; renderPickers(); });
      if (rs2) rs2.addEventListener('change', function () { recipeCtx.scene = rs2.value; renderPickers(); });
      var evBtn = $('recipe-evidence');
      if (evBtn) evBtn.addEventListener('click', evidencePick);
    } else {
      ['check-ctx', 'recipe-ctx', 'recipe-evidence'].forEach(function (id) {
        var n = $(id);
        if (n) n.style.display = 'none';
      });
    }
  }

  renderAll();
  wire();
  renderConsentUI();
  if (AN && AN.enabled()) { try { AN.pageView(location.pathname, document.referrer, lang); } catch (e) { /* ignore */ } }
  var sharedLoaded = loadFromHash();
  // #c= prefill: land on the checker with a term to verify (used by atom pages / articles)
  if (location.hash.indexOf('#c=') === 0) {
    var prefill = decodeURIComponent(location.hash.slice(3)).slice(0, 500);
    if (prefill) {
      $('checker-input').value = prefill;
      switchTab('checker');
      runCheck();
    }
  }
  if (sharedLoaded) {
    renderPickers();
    renderPreview();
    switchTab('recipe');
    toast(t('share-card-loaded'));
  }
})();
